import { C, buildBeds, buildCoop, buildFence, buildGreenhouse, buildHouse, buildLanterns, buildOrchard, buildPath, buildPond, buildWell, buildWindmill } from "../core/geometry";
import { agora, amphitheater, aqueduct, basaltHut, hotSpring, lavaLake, locomotive, obsidianSpikes, platform, railSignal, railTrack, station, statue, temple, volcano } from "./builders/antique";
import { artGallery, astronomerHut, beehive, honeyHouse, honeycombFrame, kineticSculpture, meadow, muralWall, observatoryDome, radioDish, sculptorStudio, starChart } from "./builders/bee";
import { cargoShip, castleWall, catapult, containers, fishMarket, forge, gatehouse, harborBuoys, jpBridge, keep, knightTent, koiPond, pagoda, portCrane, sakuraGrove, stoneLantern, tavern, teahouse, torii, warehouse, wharf, zenGarden } from "./builders/castle";
import { bigTop, circusRing, circusWagon, crowsNest, fairyRing, glowShrooms, mushroomBridge, mushroomHouse, pirateShip, pirateTavern, trapeze, treasureChest } from "./builders/circus";
import { buildAvenue, buildBillboard, buildCityFountain, buildCrossroad, buildMall, buildMetro, buildOffices, buildParking, buildSkyscraper, highrise } from "./builders/city";
import { barn, beehives, bridge, bungalow, chapel, civic, dwelling, gasStation, gazebo, haystacks, makeWorld, marketStall, pen, promenade, sportsField, volleyball } from "./builders/common";
import { assemblyHangar, controlCenter, fuelTanks, jungleGrove, jungleIdol, launchPad, mineEntrance, mineTower, oreCart, oreForge, orePile, roverVehicle, stiltHut, waterfall } from "./builders/mine";
import { adobe, baggage, bumperCars, camels, caravanserai, carousel, controlTower, ferrisWheel, fuelTruck, hangar, parkedPlanes, radar, rollerCoaster, runway, tent, terminal, ticketBooth, watchtower } from "./builders/park";
import { buildBeach, buildBeachBar, buildBoats, buildHotel, buildLighthouse, buildPalms, buildPier, buildPool, buildUmbrellas, it } from "./builders/resort";
import { bandShell, carillon, clayPit, coralGarden, kiln, musicShop, potteryRacks, potteryWheel, seaBeacon, seaDome, streetPiano, sunkenWreck } from "./builders/sea";
import { arcade, firGrove, firewood, foodTruck, frozenPond, iceRink, nightClub, skiLodge, snowman } from "./builders/seasonal";
import { chalet, clockTower, dryingRacks, resortRink, skiLift, snowPines, streetChimes, sundial, teaHouse, teaMill, teaTerraces, watchmakerShop } from "./builders/ski";
import { buildBusStop, buildCafe, buildParkSquare, buildPlayground, buildRoad, buildShop, buildSidewalk, buildStreetLamps, buildWaterTower, cottage } from "./builders/town";

/* ============================================================
   МИРЫ
   Каждое здание — отдельный уровень. Повторяющиеся типы
   различаются номером (n) и параметрами модели
   ============================================================ */

// короткая обёртка: builder с заранее заданными параметрами
export const B = (fn, arg) => (store) => (arg === undefined ? fn(store) : fn(arg, store));

const VILLAGE_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "brick", "sand", "hammer", "ruler", "gloves") },
  { key: "fence", icon: "🚧", global: true, make: buildFence, items: it("plank", "bolt", "hammer", "saw", "paint", "gloves") },
  { key: "house", n: 1, icon: "🏠", make: buildHouse, items: it("brick", "plank", "door", "glass", "hammer", "ladder") },
  { key: "beds", icon: "🥬", make: buildBeds, items: it("seed", "nut", "sprout", "water", "basket", "worm") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "greenhouse", icon: "🏡", make: buildGreenhouse, items: it("glass", "plank", "bolt", "plan", "screw", "toolbox") },
  { key: "orchard", icon: "🌳", make: buildOrchard, items: it("tree", "sprout", "water", "shears", "basket", "apple") },
  { key: "coop", icon: "🐔", make: buildCoop, items: it("plank", "egg", "straw", "hammer", "sand", "basket") },
  { key: "barn", icon: "🛖", make: B(barn), items: it("plank", "straw", "hammer", "paint", "bolt", "ladder") },
  { key: "house", n: 2, icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.6, body: 0xdfe8e0, roof: 0x5d7f8e, chimney: true }), items: it("brick", "plank", "door", "glass", "paint", "ladder") },
  { key: "bakery", icon: "🥖", make: B(dwelling, { w: 3.4, d: 2.8, body: 0xf0dcc0, roof: 0xb5453a, chimney: true, roofType: "hip" }), items: it("brick", "straw", "door", "glass", "basket", "hammer") },
  { key: "chapel", icon: "⛪", make: B(chapel), items: it("stone", "glass", "plank", "paint", "bulb", "ladder") },
  { key: "hay", icon: "🌾", make: B(haystacks), items: it("straw", "basket", "rope", "gloves", "shears", "cart") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "paint", "apple", "rope", "bag") },
  { key: "apiary", icon: "🍯", make: B(beehives), items: it("plank", "paint", "sprout", "basket", "gloves", "nut") },
  { key: "pen", icon: "🐑", make: B(pen), items: it("plank", "rope", "straw", "hammer", "water", "gloves") },
  { key: "house", n: 3, icon: "🏠", make: B(dwelling, { w: 3.4, d: 2.9, floors: 2, body: 0xe8d5b0, roof: 0x8a6a4a, balcony: true }), items: it("brick", "plank", "door", "glass", "ladder", "key") },
  { key: "pond", icon: "💧", make: buildPond, items: it("water", "stone", "fish", "lotus", "sand", "algae") },
  { key: "bridge", icon: "🌉", make: B(bridge), items: it("plank", "rope", "stone", "hammer", "bolt", "water") },
  { key: "windmill", icon: "🌾", make: buildWindmill, items: it("gear", "plank", "rope", "bolt", "straw", "screw") },
  { key: "house", n: 4, icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.7, body: 0xf7e0b8, roof: 0x4f8f6a, chimney: true }), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "stall", n: 2, icon: "🧺", make: B(marketStall), items: it("plank", "basket", "apple", "bag", "rope", "cart") },
  { key: "fir", icon: "🌲", make: B(firGrove), items: it("tree", "sprout", "shears", "gloves", "basket", "nut") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const TOWN_STAGES = [
  { key: "road", icon: "🛣️", global: true, make: buildRoad, items: it("cement", "cone", "paint", "ruler", "hammer", "gloves") },
  { key: "sidewalk", icon: "🚶", global: true, make: buildSidewalk, items: it("brick", "cement", "sand", "ruler", "bench", "gloves") },
  { key: "cottage", n: 1, icon: "🏘️", make: B(cottage, 0xf3e3cd), items: it("brick", "plank", "door", "glass", "ladder", "key") },
  { key: "shop", icon: "🏪", make: buildShop, items: it("glass", "cart", "bag", "paint", "bulb", "toolbox") },
  { key: "cottage", n: 2, icon: "🏘️", make: B(cottage, 0xdfe8e0), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "cafe", icon: "☕", make: buildCafe, items: it("cup", "bench", "umbrella", "glass", "paint", "plank") },
  { key: "playground", icon: "🛝", make: buildPlayground, items: it("sand", "plank", "paint", "ball", "bolt", "rope") },
  { key: "busstop", icon: "🚌", make: buildBusStop, items: it("bus", "glass", "bench", "sign", "bolt", "clock") },
  { key: "school", icon: "🏫", make: B(civic, { w: 5.4, d: 3.4, floors: 2, body: 0xf2e2c4, roof: 0xb5453a, accent: 0xd94f4f, doors: 2 }), items: it("brick", "glass", "door", "ruler", "paint", "clock") },
  { key: "cottage", n: 3, icon: "🏘️", make: B(cottage, 0xe8d5b0), items: it("brick", "plank", "door", "glass", "hammer", "key") },
  { key: "clinic", icon: "🏥", make: B(civic, { w: 4.8, d: 3.2, floors: 2, body: 0xfaf3e4, roof: 0x6b7f8e, accent: 0x4f9ec4 }), items: it("brick", "glass", "door", "pipe", "bulb", "cement") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "fire", icon: "🚒", make: B(civic, { w: 4.4, d: 3.4, floors: 1, body: 0xd94f4f, roof: 0x8a3a30, tower: true, accent: 0xf2c144, doors: 2 }), items: it("brick", "door", "ladder", "pipe", "paint", "bulb") },
  { key: "gas", icon: "⛽", make: B(gasStation), items: it("cement", "pipe", "car", "sign", "bulb", "paint") },
  { key: "sport", icon: "⚽", make: B(sportsField), items: it("ball", "paint", "sprout", "bench", "rope", "ruler") },
  { key: "bakery", icon: "🥖", make: B(dwelling, { w: 3.4, d: 2.8, body: 0xf0dcc0, roof: 0xb5453a, chimney: true, roofType: "hip" }), items: it("brick", "straw", "door", "glass", "basket", "bag") },
  { key: "townhall", icon: "🏛️", make: B(civic, { w: 5.2, d: 3.6, floors: 2, body: 0xfaf3e4, roof: 0x6b7f8e, tower: true, clock: true, columns: true, accent: 0xc9a05a }), items: it("stone", "glass", "door", "clock", "paint", "cement") },
  { key: "chapel", icon: "⛪", make: B(chapel), items: it("stone", "glass", "plank", "paint", "bulb", "ladder") },
  { key: "kiosk", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "paint", "bag", "cup", "bulb") },
  { key: "watertower", icon: "🗼", make: buildWaterTower, items: it("pipe", "bolt", "ladder", "water", "paint", "crane") },
  { key: "fountain", icon: "⛲", make: buildCityFountain, items: it("water", "stone", "pipe", "cement", "bulb", "shell") },
  { key: "cottage", n: 4, icon: "🏘️", make: B(cottage, 0xf0d8c0), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "library", icon: "🏛️", make: B(civic, { w: 4.6, d: 3.2, floors: 2, body: 0xe8dcc0, roof: 0x8a6a4a, columns: true, accent: 0x6a8fc4 }), items: it("stone", "glass", "door", "plan", "paint", "cement") },
  { key: "bridge", icon: "🌉", make: B(bridge), items: it("plank", "rope", "stone", "hammer", "bolt", "water") },
  { key: "pen", icon: "🐑", make: B(pen), items: it("plank", "rope", "straw", "hammer", "water", "gloves") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "streetlamps", icon: "💡", global: true, make: buildStreetLamps, items: it("bulb", "wire", "cement", "screw", "spark", "torch") },
];

const CITY_STAGES = [
  { key: "avenue", icon: "🛣️", global: true, make: buildAvenue, items: it("cement", "cone", "paint", "ruler", "tree", "gloves") },
  { key: "crossroad", icon: "🚦", global: true, make: buildCrossroad, items: it("sign", "wire", "paint", "cone", "bolt", "car") },
  { key: "offices", n: 1, icon: "🏢", make: buildOffices, items: it("glass", "cement", "crane", "lift", "bolt", "plan") },
  { key: "skyscraper", n: 1, icon: "🏙️", make: buildSkyscraper, items: it("glass", "crane", "cement", "lift", "bolt", "plan") },
  { key: "mall", icon: "🛍️", make: buildMall, items: it("bag", "cart", "glass", "lift", "bulb", "paint") },
  { key: "metro", icon: "🚇", make: buildMetro, items: it("tram", "cement", "sign", "ladder", "bulb", "lift") },
  { key: "parking", icon: "🅿️", make: buildParking, items: it("car", "paint", "cement", "cone", "sign", "ruler") },
  { key: "skyscraper", n: 2, icon: "🏙️", make: B(highrise, { floors: 12, w: 3.2, d: 3.2, color: 0xdfe3e6, glass: 0x6fa8c8, setback: 0.15 }), items: it("glass", "crane", "cement", "lift", "bolt", "plan") },
  { key: "bank", icon: "🏦", make: B(civic, { w: 4.8, d: 3.4, floors: 2, body: 0xe8e2d2, roof: 0x8d949a, columns: true, accent: 0xc9a05a }), items: it("stone", "glass", "door", "key", "cement", "clock") },
  { key: "billboard", icon: "📺", make: buildBillboard, items: it("paint", "bulb", "wire", "bolt", "plan", "spark") },
  { key: "offices", n: 2, icon: "🏢", make: B(highrise, { floors: 6, w: 3.6, d: 3.0, color: 0xc7bfae, glass: 0x8fbfa8 }), items: it("glass", "cement", "crane", "lift", "bolt", "plan") },
  { key: "cinema", icon: "🎬", make: B(civic, { w: 5.0, d: 3.2, floors: 1, body: 0x8a5a8c, roof: 0x5d3d63, accent: 0xf2c144, doors: 2 }), items: it("bulb", "paint", "glass", "wire", "bag", "spark") },
  { key: "fountain", icon: "⛲", make: buildCityFountain, items: it("water", "stone", "pipe", "cement", "bulb", "shell") },
  { key: "hospital", icon: "🏥", make: B(civic, { w: 5.6, d: 3.6, floors: 3, body: 0xfaf3e4, roof: 0x6b7f8e, accent: 0x4f9ec4, doors: 2 }), items: it("cement", "glass", "door", "pipe", "lift", "bulb") },
  { key: "skyscraper", n: 3, icon: "🏙️", make: B(highrise, { floors: 18, w: 3.4, d: 3.4, color: 0xa8b6c2, glass: 0x4f8eb8, setback: 0.25 }), items: it("glass", "crane", "cement", "lift", "bolt", "plan") },
  { key: "hotel", icon: "🏨", make: B(highrise, { floors: 9, w: 4.2, d: 3.2, color: 0xf0e0c8, glass: 0x9ac4d8 }), items: it("brick", "glass", "door", "key", "lift", "paint") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "offices", n: 3, icon: "🏢", make: B(highrise, { floors: 8, w: 2.8, d: 2.8, color: 0xd6cec0, glass: 0x7fb0c8 }), items: it("glass", "cement", "crane", "lift", "bolt", "plan") },
  { key: "townhall", icon: "🏛️", make: B(civic, { w: 5.4, d: 3.6, floors: 2, body: 0xfaf3e4, roof: 0x6b7f8e, tower: true, clock: true, columns: true, accent: 0xc9a05a }), items: it("stone", "glass", "door", "clock", "paint", "cement") },
  { key: "busstation", icon: "🚌", make: buildBusStop, items: it("bus", "glass", "bench", "sign", "bolt", "clock") },
  { key: "school", icon: "🏫", make: B(civic, { w: 5.2, d: 3.4, floors: 2, body: 0xf2e2c4, roof: 0xb5453a, accent: 0xd94f4f, doors: 2 }), items: it("brick", "glass", "door", "ruler", "paint", "clock") },
  { key: "kiosk", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "paint", "bag", "cup", "bulb") },
  { key: "gas", icon: "⛽", make: B(gasStation), items: it("cement", "pipe", "car", "sign", "bulb", "paint") },
  { key: "skyscraper", n: 4, icon: "🏙️", make: B(highrise, { floors: 16, w: 3.0, d: 3.0, color: 0xe0dcd2, glass: 0x5fc4e8, setback: 0.2 }), items: it("glass", "crane", "cement", "lift", "bolt", "plan") },
  { key: "library", icon: "🏛️", make: B(civic, { w: 5.0, d: 3.4, floors: 2, body: 0xe8e2d2, roof: 0x8d949a, columns: true, accent: 0x6a8fc4 }), items: it("stone", "glass", "door", "plan", "paint", "cement") },
  { key: "arcade", icon: "🕹️", make: arcade, items: it("bulb", "wire", "spark", "glass", "paint", "key") },
  { key: "offices", n: 4, icon: "🏢", make: B(highrise, { floors: 9, w: 3.4, d: 2.6, color: 0xc9d4d8, glass: 0x8fd4c4 }), items: it("glass", "cement", "crane", "lift", "bolt", "plan") },
  { key: "sport", icon: "⚽", make: B(sportsField), items: it("ball", "paint", "sprout", "bench", "rope", "ruler") },
  { key: "citylights", icon: "✨", global: true, make: buildStreetLamps, items: it("bulb", "wire", "cement", "screw", "spark", "torch") },
];

const RESORT_STAGES = [
  { key: "beach", icon: "🏖️", global: true, make: buildBeach, items: it("sand", "shell", "wave", "basket", "gloves", "sun") },
  { key: "palms", n: 1, icon: "🌴", make: buildPalms, items: it("palm", "sprout", "water", "shears", "nut", "sand") },
  { key: "umbrellas", icon: "⛱️", make: buildUmbrellas, items: it("umbrella", "towel", "rope", "plank", "paint", "sun") },
  { key: "pier", icon: "🛶", make: buildPier, items: it("plank", "rope", "bolt", "hammer", "anchor", "bulb") },
  { key: "hotel", n: 1, icon: "🏨", make: buildHotel, items: it("brick", "glass", "door", "key", "lift", "paint") },
  { key: "pool", icon: "🏊", make: buildPool, items: it("water", "pipe", "brick", "towel", "umbrella", "cement") },
  { key: "bungalow", n: 1, icon: "🛖", make: B(bungalow, 0xf6ecd8), items: it("plank", "straw", "door", "rope", "paint", "shell") },
  { key: "bar", icon: "🍹", make: buildBeachBar, items: it("drink", "plank", "straw", "cup", "bulb", "shell") },
  { key: "boats", icon: "⛵", make: buildBoats, items: it("boat", "rope", "plank", "anchor", "buoy", "wave") },
  { key: "bungalow", n: 2, icon: "🛖", make: B(bungalow, 0xe8dcc0), items: it("plank", "straw", "door", "rope", "paint", "shell") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "volley", icon: "🏐", make: B(volleyball), items: it("ball", "rope", "sand", "plank", "paint", "sun") },
  { key: "promenade", icon: "🚶", make: B(promenade), items: it("brick", "cement", "bulb", "bench", "ruler", "paint") },
  { key: "palms", n: 2, icon: "🌴", make: buildPalms, items: it("palm", "sprout", "water", "shears", "nut", "sand") },
  { key: "bungalow", n: 3, icon: "🛖", make: B(bungalow, 0xd8e4dc), items: it("plank", "straw", "door", "rope", "paint", "shell") },
  { key: "hotel", n: 2, icon: "🏨", make: B(dwelling, { w: 4.4, d: 3.2, floors: 3, body: 0xfaf0dc, roof: 0xe8746a, roofType: "flat", balcony: true, porch: false }), items: it("brick", "glass", "door", "key", "lift", "paint") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "drink", "shell", "paint", "bag") },
  { key: "fountain", icon: "⛲", make: buildCityFountain, items: it("water", "stone", "pipe", "cement", "bulb", "shell") },
  { key: "lighthouse", icon: "🗼", make: buildLighthouse, items: it("stone", "paint", "bulb", "glass", "ladder", "wire") },
  { key: "bungalow", n: 4, icon: "🛖", make: B(bungalow, 0xffe8c4), items: it("plank", "straw", "door", "rope", "paint", "shell") },
  { key: "umbrellas", n: 2, icon: "⛱️", make: buildUmbrellas, items: it("umbrella", "towel", "rope", "plank", "paint", "sun") },
  { key: "boats", n: 2, icon: "⛵", make: buildBoats, items: it("boat", "rope", "plank", "anchor", "buoy", "wave") },
  { key: "volley", n: 2, icon: "🏐", make: B(volleyball), items: it("ball", "rope", "sand", "plank", "paint", "sun") },
  { key: "palms", n: 3, icon: "🌴", make: buildPalms, items: it("palm", "sprout", "water", "shears", "nut", "sand") },
  { key: "beachlights", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "spark", "sun") },
];


const WINTER_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "sand", "gloves", "hammer", "ruler", "torch") },
  { key: "fence", icon: "🚧", global: true, make: buildFence, items: it("plank", "bolt", "hammer", "saw", "paint", "gloves") },
  { key: "house", n: 1, icon: "🏠", make: B(dwelling, { w: 3.2, d: 2.8, body: 0xe8dcc8, roof: 0xdfe8ee, chimney: true }), items: it("brick", "plank", "door", "glass", "hammer", "ladder") },
  { key: "fir", n: 1, icon: "🌲", make: B(firGrove), items: it("tree", "sprout", "shears", "gloves", "basket", "nut") },
  { key: "firewood", icon: "🪵", make: B(firewood), items: it("plank", "saw", "rope", "gloves", "basket", "hammer") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "snowman", icon: "⛄", make: B(snowman), items: it("water", "stone", "basket", "gloves", "paint", "shears") },
  { key: "barn", icon: "🛖", make: B(barn), items: it("plank", "straw", "hammer", "paint", "bolt", "ladder") },
  { key: "frozenpond", icon: "🧊", make: frozenPond, items: it("water", "stone", "fish", "algae", "gloves", "rope") },
  { key: "rink", icon: "⛸️", make: iceRink, items: it("water", "plank", "bulb", "wire", "paint", "bench") },
  { key: "house", n: 2, icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.6, body: 0xd8e0e8, roof: 0xf2f6f8, chimney: true, roofType: "hip" }), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "lodge", icon: "🎿", make: B(skiLodge), items: it("plank", "glass", "door", "bulb", "rope", "paint") },
  { key: "fir", n: 2, icon: "🌲", make: B(firGrove), items: it("tree", "sprout", "shears", "gloves", "basket", "nut") },
  { key: "chapel", icon: "⛪", make: B(chapel), items: it("stone", "glass", "plank", "paint", "bulb", "ladder") },
  { key: "bakery", icon: "🥖", make: B(dwelling, { w: 3.4, d: 2.8, body: 0xf0dcc0, roof: 0xe8eef2, chimney: true, roofType: "hip" }), items: it("brick", "straw", "door", "glass", "basket", "bag") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "paint", "cup", "rope", "bag") },
  { key: "house", n: 3, icon: "🏠", make: B(dwelling, { w: 3.4, d: 2.9, floors: 2, body: 0xdcd0c0, roof: 0xeaf0f4, balcony: true, chimney: true }), items: it("brick", "plank", "door", "glass", "ladder", "key") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "hay", icon: "🌾", make: B(haystacks), items: it("straw", "basket", "rope", "gloves", "shears", "cart") },
  { key: "windmill", icon: "🌾", make: buildWindmill, items: it("gear", "plank", "rope", "bolt", "straw", "screw") },
  { key: "house", n: 4, icon: "🏠", make: B(dwelling, { w: 3.2, d: 2.7, body: 0xe0d4e8, roof: 0xf7fbff, chimney: true }), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "snowman", n: 2, icon: "⛄", make: B(snowman), items: it("water", "stone", "basket", "gloves", "paint", "shears") },
  { key: "stall", n: 2, icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "rope", "bulb") },
  { key: "pen", icon: "🐑", make: B(pen), items: it("plank", "rope", "straw", "hammer", "water", "gloves") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const NIGHT_STAGES = [
  { key: "avenue", icon: "🛣️", global: true, make: buildAvenue, items: it("cement", "cone", "paint", "ruler", "tree", "gloves") },
  { key: "crossroad", icon: "🚦", global: true, make: buildCrossroad, items: it("sign", "wire", "paint", "cone", "bolt", "car") },
  { key: "skyscraper", n: 1, icon: "🏙️", make: buildSkyscraper, items: it("glass", "crane", "cement", "lift", "bolt", "plan") },
  { key: "club", icon: "🪩", make: nightClub, items: it("bulb", "wire", "spark", "paint", "drink", "glass") },
  { key: "offices", n: 1, icon: "🏢", make: buildOffices, items: it("glass", "cement", "crane", "lift", "bolt", "plan") },
  { key: "mall", icon: "🛍️", make: buildMall, items: it("bag", "cart", "glass", "lift", "bulb", "paint") },
  { key: "metro", icon: "🚇", make: buildMetro, items: it("tram", "cement", "sign", "ladder", "bulb", "lift") },
  { key: "billboard", icon: "📺", make: buildBillboard, items: it("paint", "bulb", "wire", "bolt", "plan", "spark") },
  { key: "skyscraper", n: 2, icon: "🏙️", make: B(highrise, { floors: 13, w: 3.2, d: 3.2, color: 0x3a4356, glass: 0x7fd0ff, setback: 0.16 }), items: it("glass", "crane", "cement", "lift", "bolt", "plan") },
  { key: "foodtruck", icon: "🌮", make: foodTruck, items: it("cup", "drink", "car", "bulb", "bag", "basket") },
  { key: "arcade", icon: "🕹️", make: arcade, items: it("bulb", "wire", "spark", "glass", "paint", "key") },
  { key: "hotel", icon: "🏨", make: B(highrise, { floors: 9, w: 4.2, d: 3.2, color: 0x4a4458, glass: 0xffc46b }), items: it("brick", "glass", "door", "key", "lift", "paint") },
  { key: "cinema", icon: "🎬", make: B(civic, { w: 5.0, d: 3.2, floors: 1, body: 0x3d2f52, roof: 0x2a2038, accent: 0xff5ac4, doors: 2 }), items: it("bulb", "paint", "glass", "wire", "bag", "spark") },
  { key: "fountain", icon: "⛲", make: buildCityFountain, items: it("water", "stone", "pipe", "cement", "bulb", "shell") },
  { key: "parking", icon: "🅿️", make: buildParking, items: it("car", "paint", "cement", "cone", "sign", "ruler") },
  { key: "offices", n: 2, icon: "🏢", make: B(highrise, { floors: 7, w: 3.6, d: 3.0, color: 0x37405a, glass: 0x8fe0d8 }), items: it("glass", "cement", "crane", "lift", "bolt", "plan") },
  { key: "skyscraper", n: 3, icon: "🏙️", make: B(highrise, { floors: 19, w: 3.4, d: 3.4, color: 0x2f3a4e, glass: 0x5fb8ff, setback: 0.24 }), items: it("glass", "crane", "cement", "lift", "bolt", "plan") },
  { key: "bank", icon: "🏦", make: B(civic, { w: 4.8, d: 3.4, floors: 2, body: 0x494256, roof: 0x8d949a, columns: true, accent: 0xffd45a }), items: it("stone", "glass", "door", "key", "cement", "clock") },
  { key: "kiosk", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "paint", "bag", "cup", "bulb") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "busstation", icon: "🚌", make: buildBusStop, items: it("bus", "glass", "bench", "sign", "bolt", "clock") },
  { key: "hospital", icon: "🏥", make: B(civic, { w: 5.6, d: 3.6, floors: 3, body: 0x4a5060, roof: 0x6b7f8e, accent: 0x4f9ec4, doors: 2 }), items: it("cement", "glass", "door", "pipe", "lift", "bulb") },
  { key: "townhall", icon: "🏛️", make: B(civic, { w: 5.4, d: 3.6, floors: 2, body: 0x4e4a5c, roof: 0x6b7f8e, tower: true, clock: true, columns: true, accent: 0xffd45a }), items: it("stone", "glass", "door", "clock", "paint", "cement") },
  { key: "club", n: 2, icon: "🪩", make: nightClub, items: it("bulb", "wire", "spark", "paint", "drink", "glass") },
  { key: "arcade", n: 2, icon: "🕹️", make: arcade, items: it("bulb", "wire", "spark", "glass", "paint", "key") },
  { key: "skyscraper", n: 4, icon: "🏙️", make: B(highrise, { floors: 15, w: 3.0, d: 3.0, color: 0x453a68, glass: 0xff6fd4, setback: 0.18 }), items: it("glass", "crane", "cement", "lift", "bolt", "plan") },
  { key: "foodtruck", n: 2, icon: "🌮", make: foodTruck, items: it("cup", "drink", "car", "bulb", "bag", "basket") },
  { key: "citylights", icon: "✨", global: true, make: buildStreetLamps, items: it("bulb", "wire", "cement", "screw", "spark", "torch") },
];


const AIRPORT_STAGES = [
  { key: "runway", icon: "🛫", global: true, make: runway, items: it("cement", "cone", "paint", "ruler", "bulb", "gloves") },
  { key: "terminal", icon: "🏢", make: B(terminal), items: it("glass", "cement", "door", "lift", "plan", "bulb") },
  { key: "tower", icon: "🗼", make: controlTower, items: it("glass", "wire", "bolt", "plan", "bulb", "lift") },
  { key: "hangar", n: 1, icon: "🛩️", make: B(hangar), items: it("bolt", "crane", "cement", "paint", "ladder", "plan") },
  { key: "plane", n: 1, icon: "✈️", make: parkedPlanes, items: it("bolt", "gear", "glass", "wire", "paint", "screw") },
  { key: "radar", icon: "📡", make: radar, items: it("wire", "bolt", "gear", "plan", "screw", "bulb") },
  { key: "fuel", icon: "⛽", make: B(fuelTruck), items: it("pipe", "car", "bolt", "sign", "cone", "wire") },
  { key: "baggage", icon: "🧳", make: B(baggage), items: it("cart", "bag", "gear", "wire", "bolt", "cement") },
  { key: "parking", icon: "🅿️", make: buildParking, items: it("car", "paint", "cement", "cone", "sign", "ruler") },
  { key: "hangar", n: 2, icon: "🛩️", make: B(hangar), items: it("bolt", "crane", "cement", "paint", "ladder", "plan") },
  { key: "cafe", icon: "☕", make: buildCafe, items: it("cup", "bench", "umbrella", "glass", "paint", "plank") },
  { key: "hotel", icon: "🏨", make: B(highrise, { floors: 8, w: 3.8, d: 3.0, color: 0xe4e0d6, glass: 0x8fbfd8 }), items: it("brick", "glass", "door", "key", "lift", "paint") },
  { key: "busstation", icon: "🚌", make: buildBusStop, items: it("bus", "glass", "bench", "sign", "bolt", "clock") },
  { key: "plane", n: 2, icon: "✈️", make: parkedPlanes, items: it("bolt", "gear", "glass", "wire", "paint", "screw") },
  { key: "offices", icon: "🏢", make: B(highrise, { floors: 6, w: 3.2, d: 2.8, color: 0xd6d2c8, glass: 0x7fb0c8 }), items: it("glass", "cement", "crane", "lift", "bolt", "plan") },
  { key: "kiosk", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "paint", "bag", "cup", "bulb") },
  { key: "watertower", icon: "🗼", make: buildWaterTower, items: it("pipe", "bolt", "ladder", "water", "paint", "crane") },
  { key: "clinic", icon: "🏥", make: B(civic, { w: 4.6, d: 3.2, floors: 2, body: 0xfaf3e4, roof: 0x6b7f8e, accent: 0x4f9ec4 }), items: it("brick", "glass", "door", "pipe", "bulb", "cement") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "hangar", n: 3, icon: "🛩️", make: B(hangar), items: it("bolt", "crane", "cement", "paint", "ladder", "plan") },
  { key: "plane", n: 3, icon: "✈️", make: parkedPlanes, items: it("bolt", "gear", "glass", "wire", "paint", "screw") },
  { key: "fuel", n: 2, icon: "⛽", make: B(fuelTruck), items: it("pipe", "car", "bolt", "sign", "cone", "wire") },
  { key: "baggage", n: 2, icon: "🧳", make: B(baggage), items: it("cart", "bag", "gear", "wire", "bolt", "cement") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "citylights", icon: "✨", global: true, make: buildStreetLamps, items: it("bulb", "wire", "cement", "screw", "spark", "torch") },
];

const DESERT_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "sand", "gloves", "hammer", "ruler", "basket") },
  { key: "adobe", n: 1, icon: "🛖", make: B(adobe, { w: 3.0, d: 2.8 }), items: it("brick", "sand", "door", "plank", "water", "gloves") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "palms", n: 1, icon: "🌴", make: buildPalms, items: it("palm", "sprout", "water", "shears", "nut", "sand") },
  { key: "tent", n: 1, icon: "⛺", make: B(tent), items: it("rope", "plank", "paint", "basket", "cup", "gloves") },
  { key: "adobe", n: 2, icon: "🛖", make: B(adobe, { w: 3.4, d: 2.6, floors: 2, color: 0xe0bd91 }), items: it("brick", "sand", "door", "ladder", "plank", "key") },
  { key: "oasis", icon: "💧", make: buildPond, items: it("water", "stone", "fish", "lotus", "algae", "sand") },
  { key: "camel", icon: "🐪", make: B(camels), items: it("rope", "straw", "water", "basket", "gloves", "bag") },
  { key: "caravan", icon: "🏛️", make: B(caravanserai), items: it("brick", "sand", "door", "cement", "paint", "bag") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "paint", "bag", "cup", "rope") },
  { key: "watchtower", icon: "🗼", make: B(watchtower), items: it("stone", "brick", "ladder", "torch", "rope", "paint") },
  { key: "adobe", n: 3, icon: "🛖", make: B(adobe, { w: 2.8, d: 2.6, color: 0xcfa878 }), items: it("brick", "sand", "door", "plank", "water", "gloves") },
  { key: "tent", n: 2, icon: "⛺", make: B(tent), items: it("rope", "plank", "paint", "basket", "cup", "gloves") },
  { key: "palms", n: 2, icon: "🌴", make: buildPalms, items: it("palm", "sprout", "water", "shears", "nut", "sand") },
  { key: "bakery", icon: "🥖", make: B(adobe, { w: 3.2, d: 2.8, color: 0xdcb686 }), items: it("brick", "straw", "door", "basket", "bag", "hammer") },
  { key: "chapel", icon: "🕌", make: B(watchtower), items: it("stone", "brick", "paint", "bulb", "ladder", "glass") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "hay", icon: "🌾", make: B(haystacks), items: it("straw", "basket", "rope", "gloves", "shears", "cart") },
  { key: "pen", icon: "🐑", make: B(pen), items: it("plank", "rope", "straw", "hammer", "water", "gloves") },
  { key: "adobe", n: 4, icon: "🛖", make: B(adobe, { w: 3.2, d: 3.0, floors: 2, color: 0xf7c48f }), items: it("brick", "sand", "door", "ladder", "plank", "key") },
  { key: "tent", n: 3, icon: "⛺", make: B(tent), items: it("rope", "plank", "paint", "basket", "cup", "gloves") },
  { key: "camel", n: 2, icon: "🐪", make: B(camels), items: it("rope", "straw", "water", "basket", "gloves", "bag") },
  { key: "watchtower", n: 2, icon: "🗼", make: B(watchtower), items: it("stone", "brick", "ladder", "torch", "rope", "paint") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const PARK_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "brick", "sand", "hammer", "ruler", "gloves") },
  { key: "fence", icon: "🚧", global: true, make: buildFence, items: it("plank", "bolt", "hammer", "saw", "paint", "gloves") },
  { key: "ticket", icon: "🎫", make: B(ticketBooth), items: it("plank", "paint", "bulb", "bag", "key", "sign") },
  { key: "carousel", icon: "🎠", make: carousel, items: it("gear", "paint", "bulb", "plank", "bolt", "spark") },
  { key: "ferris", icon: "🎡", make: ferrisWheel, items: it("gear", "crane", "bolt", "wire", "paint", "bulb") },
  { key: "foodtruck", icon: "🌮", make: foodTruck, items: it("cup", "drink", "car", "bulb", "bag", "basket") },
  { key: "bumper", icon: "🚗", make: B(bumperCars), items: it("car", "wire", "paint", "bulb", "bolt", "cement") },
  { key: "coaster", icon: "🎢", make: rollerCoaster, items: it("crane", "bolt", "gear", "paint", "cement", "plan") },
  { key: "arcade", icon: "🕹️", make: arcade, items: it("bulb", "wire", "spark", "glass", "paint", "key") },
  { key: "stall", n: 1, icon: "🧺", make: B(marketStall), items: it("plank", "basket", "paint", "bag", "cup", "drink") },
  { key: "fountain", icon: "⛲", make: buildCityFountain, items: it("water", "stone", "pipe", "cement", "bulb", "shell") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "cafe", icon: "☕", make: buildCafe, items: it("cup", "bench", "umbrella", "glass", "paint", "plank") },
  { key: "playground", icon: "🛝", make: buildPlayground, items: it("sand", "plank", "paint", "ball", "bolt", "rope") },
  { key: "stall", n: 2, icon: "🧺", make: B(marketStall), items: it("plank", "basket", "paint", "bag", "cup", "drink") },
  { key: "pond", icon: "💧", make: buildPond, items: it("water", "stone", "fish", "lotus", "sand", "algae") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "busstop", icon: "🚌", make: buildBusStop, items: it("bus", "glass", "bench", "sign", "bolt", "clock") },
  { key: "billboard", icon: "📺", make: buildBillboard, items: it("paint", "bulb", "wire", "bolt", "plan", "spark") },
  { key: "carousel", n: 2, icon: "🎠", make: carousel, items: it("gear", "paint", "bulb", "plank", "bolt", "spark") },
  { key: "bumper", n: 2, icon: "🚗", make: B(bumperCars), items: it("car", "wire", "paint", "bulb", "bolt", "cement") },
  { key: "ticket", n: 2, icon: "🎫", make: B(ticketBooth), items: it("plank", "paint", "bulb", "bag", "key", "sign") },
  { key: "sport", icon: "⚽", make: B(sportsField), items: it("ball", "paint", "sprout", "bench", "rope", "ruler") },
  { key: "coaster", n: 2, icon: "🎢", make: rollerCoaster, items: it("crane", "bolt", "gear", "paint", "cement", "plan") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];


const CASTLE_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "brick", "sand", "hammer", "ruler", "gloves") },
  { key: "gatehouse", icon: "🚪", make: B(gatehouse), items: it("stone", "plank", "chain", "bolt", "rope", "hammer") },
  { key: "wall", n: 1, icon: "🧱", make: B(castleWall), items: it("stone", "brick", "cement", "hammer", "ruler", "gloves") },
  { key: "keep", icon: "🏰", make: B(keep), items: it("stone", "brick", "door", "ladder", "torch", "paint") },
  { key: "forge", icon: "⚒️", make: forge, items: it("hammer", "bolt", "gear", "torch", "cement", "screw") },
  { key: "tavern", icon: "🍺", make: B(tavern), items: it("plank", "brick", "door", "cup", "basket", "bulb") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "tent", n: 1, icon: "⛺", make: B(knightTent), items: it("rope", "plank", "paint", "shears", "bag", "gloves") },
  { key: "wall", n: 2, icon: "🧱", make: B(castleWall), items: it("stone", "brick", "cement", "hammer", "ruler", "gloves") },
  { key: "catapult", icon: "🎯", make: B(catapult), items: it("plank", "rope", "gear", "bolt", "stone", "hammer") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "apple", "bag", "rope", "cart") },
  { key: "watchtower", icon: "🗼", make: B(watchtower), items: it("stone", "brick", "ladder", "torch", "rope", "paint") },
  { key: "chapel", icon: "⛪", make: B(chapel), items: it("stone", "glass", "plank", "paint", "bulb", "ladder") },
  { key: "barn", icon: "🛖", make: B(barn), items: it("plank", "straw", "hammer", "paint", "bolt", "ladder") },
  { key: "tent", n: 2, icon: "⛺", make: B(knightTent), items: it("rope", "plank", "paint", "shears", "bag", "gloves") },
  { key: "pen", icon: "🐑", make: B(pen), items: it("plank", "rope", "straw", "hammer", "water", "gloves") },
  { key: "forge", n: 2, icon: "⚒️", make: forge, items: it("hammer", "bolt", "gear", "torch", "cement", "screw") },
  { key: "hay", icon: "🌾", make: B(haystacks), items: it("straw", "basket", "rope", "gloves", "shears", "cart") },
  { key: "wall", n: 3, icon: "🧱", make: B(castleWall), items: it("stone", "brick", "cement", "hammer", "ruler", "gloves") },
  { key: "catapult", n: 2, icon: "🎯", make: B(catapult), items: it("plank", "rope", "gear", "bolt", "stone", "hammer") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const SAKURA_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "sand", "gloves", "hammer", "ruler", "basket") },
  { key: "torii", n: 1, icon: "⛩️", make: B(torii), items: it("plank", "paint", "bolt", "rope", "hammer", "ladder") },
  { key: "teahouse", icon: "🍵", make: B(teahouse), items: it("plank", "glass", "door", "cup", "paint", "rope") },
  { key: "sakura", n: 1, icon: "🌸", make: B(sakuraGrove), items: it("tree", "sprout", "water", "shears", "basket", "nut") },
  { key: "lantern", n: 1, icon: "🏮", make: B(stoneLantern), items: it("stone", "bulb", "candle", "cement", "paint", "spark") },
  { key: "koipond", icon: "🎏", make: koiPond, items: it("water", "stone", "fish", "lotus", "algae", "sand") },
  { key: "pagoda", icon: "🏯", make: B(pagoda), items: it("plank", "paint", "glass", "ladder", "bolt", "bulb") },
  { key: "zen", icon: "🪨", make: B(zenGarden), items: it("stone", "sand", "shears", "gloves", "basket", "ruler") },
  { key: "jpbridge", icon: "🌉", make: B(jpBridge), items: it("plank", "paint", "bolt", "rope", "hammer", "water") },
  { key: "sakura", n: 2, icon: "🌸", make: B(sakuraGrove), items: it("tree", "sprout", "water", "shears", "basket", "nut") },
  { key: "house", n: 1, icon: "🏠", make: B(dwelling, { w: 3.2, d: 2.8, body: 0xf2ead6, roof: 0x3f4a5c, roofType: "hip" }), items: it("plank", "glass", "door", "paint", "hammer", "key") },
  { key: "lantern", n: 2, icon: "🏮", make: B(stoneLantern), items: it("stone", "bulb", "candle", "cement", "paint", "spark") },
  { key: "torii", n: 2, icon: "⛩️", make: B(torii), items: it("plank", "paint", "bolt", "rope", "hammer", "ladder") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "rope", "apple") },
  { key: "beds", icon: "🥬", make: buildBeds, items: it("seed", "nut", "sprout", "water", "basket", "worm") },
  { key: "house", n: 2, icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.6, body: 0xe8dcc4, roof: 0x4a5a48, roofType: "hip" }), items: it("plank", "glass", "door", "paint", "hammer", "key") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "sakura", n: 3, icon: "🌸", make: B(sakuraGrove), items: it("tree", "sprout", "water", "shears", "basket", "nut") },
  { key: "zen", n: 2, icon: "🪨", make: B(zenGarden), items: it("stone", "sand", "shears", "gloves", "basket", "ruler") },
  { key: "pagoda", n: 2, icon: "🏯", make: B(pagoda), items: it("plank", "paint", "glass", "ladder", "bolt", "bulb") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const HARBOR_STAGES = [
  { key: "wharf", n: 1, icon: "⚓", make: B(wharf), items: it("plank", "rope", "bolt", "hammer", "anchor", "cement") },
  { key: "warehouse", n: 1, icon: "🏭", make: B(warehouse), items: it("cement", "bolt", "door", "crane", "paint", "glass") },
  { key: "crane", n: 1, icon: "🏗️", make: portCrane, items: it("crane", "gear", "bolt", "wire", "paint", "plan") },
  { key: "containers", n: 1, icon: "📦", make: B(containers), items: it("bag", "bolt", "paint", "crane", "cart", "cement") },
  { key: "ship", n: 1, icon: "🚢", make: cargoShip, items: it("bolt", "paint", "anchor", "rope", "gear", "wave") },
  { key: "fishmarket", icon: "🐟", make: B(fishMarket), items: it("fish", "basket", "plank", "bag", "water", "cup") },
  { key: "lighthouse", icon: "🗼", make: buildLighthouse, items: it("stone", "paint", "bulb", "glass", "ladder", "wire") },
  { key: "buoys", icon: "🛟", make: harborBuoys, items: it("buoy", "rope", "paint", "bulb", "anchor", "wave") },
  { key: "wharf", n: 2, icon: "⚓", make: B(wharf), items: it("plank", "rope", "bolt", "hammer", "anchor", "cement") },
  { key: "boats", icon: "⛵", make: buildBoats, items: it("boat", "rope", "plank", "anchor", "buoy", "wave") },
  { key: "crane", n: 2, icon: "🏗️", make: portCrane, items: it("crane", "gear", "bolt", "wire", "paint", "plan") },
  { key: "warehouse", n: 2, icon: "🏭", make: B(warehouse), items: it("cement", "bolt", "door", "crane", "paint", "glass") },
  { key: "containers", n: 2, icon: "📦", make: B(containers), items: it("bag", "bolt", "paint", "crane", "cart", "cement") },
  { key: "cafe", icon: "☕", make: buildCafe, items: it("cup", "bench", "umbrella", "glass", "paint", "plank") },
  { key: "ship", n: 2, icon: "🚢", make: cargoShip, items: it("bolt", "paint", "anchor", "rope", "gear", "wave") },
  { key: "promenade", icon: "🚶", make: B(promenade), items: it("brick", "cement", "bulb", "bench", "ruler", "paint") },
  { key: "gas", icon: "⛽", make: B(gasStation), items: it("cement", "pipe", "car", "sign", "bulb", "paint") },
  { key: "parking", icon: "🅿️", make: buildParking, items: it("car", "paint", "cement", "cone", "sign", "ruler") },
  { key: "watertower", icon: "🗼", make: buildWaterTower, items: it("pipe", "bolt", "ladder", "water", "paint", "crane") },
  { key: "busstop", icon: "🚌", make: buildBusStop, items: it("bus", "glass", "bench", "sign", "bolt", "clock") },
  { key: "streetlamps", icon: "💡", global: true, make: buildStreetLamps, items: it("bulb", "wire", "cement", "screw", "spark", "torch") },
];


const ANTIQUE_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "brick", "sand", "hammer", "ruler", "gloves") },
  { key: "agora", icon: "🏛️", make: B(agora), items: it("stone", "cement", "paint", "basket", "cup", "ruler") },
  { key: "temple", n: 1, icon: "🏛️", make: B(temple), items: it("stone", "cement", "ladder", "hammer", "plan", "gold") },
  { key: "statue", n: 1, icon: "🗿", make: B(statue), items: it("stone", "shears", "hammer", "paint", "cement", "gold") },
  { key: "amphi", icon: "🎭", make: B(amphitheater), items: it("stone", "cement", "bench", "ruler", "hammer", "paint") },
  { key: "aqueduct", n: 1, icon: "🌉", make: B(aqueduct), items: it("stone", "cement", "water", "pipe", "ruler", "crane") },
  { key: "house", n: 1, icon: "🏠", make: B(dwelling, { w: 3.2, d: 2.8, body: 0xf2ece0, roof: 0xc46a3f, roofType: "hip" }), items: it("brick", "cement", "door", "glass", "paint", "key") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "apple", "bag", "rope", "cup") },
  { key: "statue", n: 2, icon: "🗿", make: B(statue), items: it("stone", "shears", "hammer", "paint", "cement", "gold") },
  { key: "fountain", icon: "⛲", make: buildCityFountain, items: it("water", "stone", "pipe", "cement", "bulb", "shell") },
  { key: "house", n: 2, icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.6, floors: 2, body: 0xe8e0d0, roof: 0xc46a3f, roofType: "hip" }), items: it("brick", "cement", "door", "glass", "ladder", "key") },
  { key: "aqueduct", n: 2, icon: "🌉", make: B(aqueduct), items: it("stone", "cement", "water", "pipe", "ruler", "crane") },
  { key: "temple", n: 2, icon: "🏛️", make: B(temple), items: it("stone", "cement", "ladder", "hammer", "plan", "gold") },
  { key: "orchard", icon: "🌳", make: buildOrchard, items: it("tree", "sprout", "water", "shears", "basket", "apple") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "library", icon: "📚", make: B(civic, { w: 4.8, d: 3.2, floors: 2, body: 0xf2ece0, roof: 0xc46a3f, columns: true, accent: 0xc9a05a }), items: it("stone", "glass", "door", "plan", "paint", "cement") },
  { key: "pen", icon: "🐑", make: B(pen), items: it("plank", "rope", "straw", "hammer", "water", "gloves") },
  { key: "watchtower", icon: "🗼", make: B(watchtower), items: it("stone", "brick", "ladder", "torch", "rope", "paint") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const VOLCANO_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "sand", "gloves", "hammer", "ruler", "cement") },
  { key: "volcano", icon: "🌋", make: volcano, items: it("stone", "torch", "cement", "gloves", "crane", "spark") },
  { key: "hut", n: 1, icon: "🛖", make: B(basaltHut), items: it("stone", "straw", "door", "rope", "torch", "gloves") },
  { key: "spikes", n: 1, icon: "🗿", make: B(obsidianSpikes), items: it("stone", "shears", "gloves", "hammer", "spark", "torch") },
  { key: "lavalake", icon: "🔥", make: lavaLake, items: it("stone", "torch", "cement", "spark", "gloves", "bulb") },
  { key: "spring", icon: "♨️", make: hotSpring, items: it("water", "stone", "pipe", "cement", "towel", "gloves") },
  { key: "hut", n: 2, icon: "🛖", make: B(basaltHut), items: it("stone", "straw", "door", "rope", "torch", "gloves") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "watchtower", icon: "🗼", make: B(watchtower), items: it("stone", "brick", "ladder", "torch", "rope", "paint") },
  { key: "spikes", n: 2, icon: "🗿", make: B(obsidianSpikes), items: it("stone", "shears", "gloves", "hammer", "spark", "torch") },
  { key: "forge", icon: "⚒️", make: forge, items: it("hammer", "bolt", "gear", "torch", "cement", "screw") },
  { key: "hut", n: 3, icon: "🛖", make: B(basaltHut), items: it("stone", "straw", "door", "rope", "torch", "gloves") },
  { key: "tent", icon: "⛺", make: B(tent), items: it("rope", "plank", "paint", "basket", "cup", "gloves") },
  { key: "spring", n: 2, icon: "♨️", make: hotSpring, items: it("water", "stone", "pipe", "cement", "towel", "gloves") },
  { key: "palms", icon: "🌴", make: buildPalms, items: it("palm", "sprout", "water", "shears", "nut", "sand") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "rope", "apple") },
  { key: "bridge", icon: "🌉", make: B(bridge), items: it("plank", "rope", "stone", "hammer", "bolt", "water") },
  { key: "lighthouse", icon: "🗼", make: buildLighthouse, items: it("stone", "paint", "bulb", "glass", "ladder", "wire") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const RAILWAY_STAGES = [
  { key: "track", icon: "🛤️", global: true, make: B(railTrack), items: it("bolt", "plank", "cement", "hammer", "ruler", "gloves") },
  { key: "station", icon: "🚉", make: B(station), items: it("brick", "glass", "door", "clock", "cement", "paint") },
  { key: "platform", n: 1, icon: "🚏", make: B(platform), items: it("cement", "bolt", "bench", "bulb", "sign", "ruler") },
  { key: "train", icon: "🚂", make: locomotive, items: it("gear", "bolt", "pipe", "wire", "paint", "crane") },
  { key: "signal", n: 1, icon: "🚦", make: railSignal, items: it("sign", "wire", "bulb", "bolt", "water", "paint") },
  { key: "warehouse", n: 1, icon: "🏭", make: B(warehouse), items: it("cement", "bolt", "door", "crane", "paint", "glass") },
  { key: "watertower", icon: "🗼", make: buildWaterTower, items: it("pipe", "bolt", "ladder", "water", "paint", "crane") },
  { key: "platform", n: 2, icon: "🚏", make: B(platform), items: it("cement", "bolt", "bench", "bulb", "sign", "ruler") },
  { key: "cafe", icon: "☕", make: buildCafe, items: it("cup", "bench", "umbrella", "glass", "paint", "plank") },
  { key: "containers", icon: "📦", make: B(containers), items: it("bag", "bolt", "paint", "crane", "cart", "cement") },
  { key: "crane", icon: "🏗️", make: portCrane, items: it("crane", "gear", "bolt", "wire", "paint", "plan") },
  { key: "signal", n: 2, icon: "🚦", make: railSignal, items: it("sign", "wire", "bulb", "bolt", "water", "paint") },
  { key: "house", n: 1, icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.6, body: 0xe8dcc4, roof: 0x5d6a72, chimney: true }), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "warehouse", n: 2, icon: "🏭", make: B(warehouse), items: it("cement", "bolt", "door", "crane", "paint", "glass") },
  { key: "parking", icon: "🅿️", make: buildParking, items: it("car", "paint", "cement", "cone", "sign", "ruler") },
  { key: "kiosk", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "bulb", "clock") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "gas", icon: "⛽", make: B(gasStation), items: it("cement", "pipe", "car", "sign", "bulb", "paint") },
  { key: "busstop", icon: "🚌", make: buildBusStop, items: it("bus", "glass", "bench", "sign", "bolt", "clock") },
  { key: "streetlamps", icon: "💡", global: true, make: buildStreetLamps, items: it("bulb", "wire", "cement", "screw", "spark", "torch") },
];


const MINE_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "brick", "sand", "hammer", "ruler", "gloves") },
  { key: "mine", icon: "⛏️", make: mineEntrance, items: it("stone", "plank", "torch", "bolt", "rope", "gloves") },
  { key: "orecart", n: 1, icon: "🛒", make: B(oreCart), items: it("cart", "stone", "bolt", "plank", "gear", "rope") },
  { key: "minetower", icon: "🗼", make: mineTower, items: it("plank", "gear", "rope", "bolt", "crane", "chain") },
  { key: "forge", icon: "⚒️", make: oreForge, items: it("hammer", "bolt", "gear", "torch", "cement", "screw") },
  { key: "orepile", n: 1, icon: "💎", make: B(orePile), items: it("stone", "gem", "gloves", "cart", "basket", "hammer") },
  { key: "house", n: 1, icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.6, body: 0xc9b89a, roof: 0x6e6a66, chimney: true }), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "orecart", n: 2, icon: "🛒", make: B(oreCart), items: it("cart", "stone", "bolt", "plank", "gear", "rope") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "rope", "apple") },
  { key: "orepile", n: 2, icon: "💎", make: B(orePile), items: it("stone", "gem", "gloves", "cart", "basket", "hammer") },
  { key: "house", n: 2, icon: "🏠", make: B(dwelling, { w: 3.2, d: 2.8, floors: 2, body: 0xd4c4a8, roof: 0x5a5652 }), items: it("brick", "plank", "door", "glass", "ladder", "key") },
  { key: "watchtower", icon: "🗼", make: B(watchtower), items: it("stone", "brick", "ladder", "torch", "rope", "paint") },
  { key: "chapel", icon: "⛪", make: B(chapel), items: it("stone", "glass", "plank", "paint", "bulb", "ladder") },
  { key: "mine", n: 2, icon: "⛏️", make: mineEntrance, items: it("stone", "plank", "torch", "bolt", "rope", "gloves") },
  { key: "firewood", icon: "🪵", make: B(firewood), items: it("log", "saw", "gloves", "rope", "cart", "hammer") },
  { key: "pen", icon: "🐑", make: B(pen), items: it("plank", "rope", "straw", "hammer", "water", "gloves") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const JUNGLE_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "sand", "gloves", "shears", "ruler", "basket") },
  { key: "grove", n: 1, icon: "🌴", make: jungleGrove, items: it("palm", "sprout", "water", "shears", "nut", "seed") },
  { key: "stilthut", n: 1, icon: "🛖", make: B(stiltHut), items: it("plank", "straw", "rope", "door", "bamboo", "gloves") },
  { key: "waterfall", icon: "💦", make: waterfall, items: it("water", "stone", "pipe", "algae", "fish", "shell") },
  { key: "idol", n: 1, icon: "🗿", make: B(jungleIdol), items: it("stone", "shears", "paint", "gold", "hammer", "gloves") },
  { key: "grove", n: 2, icon: "🌴", make: jungleGrove, items: it("palm", "sprout", "water", "shears", "nut", "seed") },
  { key: "stilthut", n: 2, icon: "🛖", make: B(stiltHut), items: it("plank", "straw", "rope", "door", "bamboo", "gloves") },
  { key: "pond", icon: "💧", make: buildPond, items: it("water", "stone", "fish", "lotus", "algae", "sand") },
  { key: "bridge", icon: "🌉", make: B(bridge), items: it("plank", "rope", "stone", "hammer", "bolt", "water") },
  { key: "beds", icon: "🥬", make: buildBeds, items: it("seed", "nut", "sprout", "water", "basket", "worm") },
  { key: "idol", n: 2, icon: "🗿", make: B(jungleIdol), items: it("stone", "shears", "paint", "gold", "hammer", "gloves") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "apple", "bag", "rope", "cup") },
  { key: "grove", n: 3, icon: "🌴", make: jungleGrove, items: it("palm", "sprout", "water", "shears", "nut", "seed") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "coop", icon: "🐔", make: buildCoop, items: it("plank", "straw", "seed", "hammer", "water", "egg") },
  { key: "orchard", icon: "🌳", make: buildOrchard, items: it("tree", "sprout", "water", "shears", "basket", "apple") },
  { key: "watchtower", icon: "🗼", make: B(watchtower), items: it("stone", "brick", "ladder", "torch", "rope", "paint") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const SPACE_STAGES = [
  { key: "pad", icon: "🚀", global: true, make: launchPad, items: it("cement", "bolt", "crane", "pipe", "wire", "plan") },
  { key: "control", icon: "🛰️", make: B(controlCenter), items: it("glass", "wire", "bolt", "plan", "bulb", "cement") },
  { key: "hangar", n: 1, icon: "🏭", make: B(assemblyHangar), items: it("cement", "bolt", "door", "crane", "paint", "glass") },
  { key: "fuel", icon: "⛽", make: B(fuelTanks), items: it("pipe", "bolt", "cement", "sign", "wire", "gear") },
  { key: "rover", n: 1, icon: "🛻", make: B(roverVehicle), items: it("car", "gear", "bolt", "wire", "glass", "paint") },
  { key: "radar", icon: "📡", make: radar, items: it("wire", "bolt", "gear", "plan", "screw", "bulb") },
  { key: "warehouse", icon: "📦", make: B(warehouse), items: it("cement", "bolt", "door", "crane", "paint", "glass") },
  { key: "hangar", n: 2, icon: "🏭", make: B(assemblyHangar), items: it("cement", "bolt", "door", "crane", "paint", "glass") },
  { key: "rover", n: 2, icon: "🛻", make: B(roverVehicle), items: it("car", "gear", "bolt", "wire", "glass", "paint") },
  { key: "offices", icon: "🏢", make: B(highrise, { floors: 5, w: 3.0, d: 2.6, color: 0xd4dae0, glass: 0x6fc4e0 }), items: it("glass", "cement", "crane", "lift", "bolt", "plan") },
  { key: "watertower", icon: "🗼", make: buildWaterTower, items: it("pipe", "bolt", "ladder", "water", "paint", "crane") },
  { key: "containers", icon: "📦", make: B(containers), items: it("bag", "bolt", "paint", "crane", "cart", "cement") },
  { key: "parking", icon: "🅿️", make: buildParking, items: it("car", "paint", "cement", "cone", "sign", "ruler") },
  { key: "cafe", icon: "☕", make: buildCafe, items: it("cup", "bench", "umbrella", "glass", "paint", "plank") },
  { key: "crane", icon: "🏗️", make: portCrane, items: it("crane", "gear", "bolt", "wire", "paint", "plan") },
  { key: "signal", icon: "🚦", make: railSignal, items: it("sign", "wire", "bulb", "bolt", "water", "paint") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "streetlamps", icon: "💡", global: true, make: buildStreetLamps, items: it("bulb", "wire", "cement", "screw", "spark", "torch") },
];


const CIRCUS_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "brick", "sand", "hammer", "ruler", "paint") },
  { key: "bigtop", icon: "🎪", make: bigTop, items: it("rope", "paint", "plank", "bulb", "bolt", "ladder") },
  { key: "ring", icon: "⭕", make: B(circusRing), items: it("sand", "plank", "paint", "bench", "rope", "ruler") },
  { key: "wagon", n: 1, icon: "🚐", make: B(circusWagon), items: it("plank", "paint", "car", "bulb", "key", "gear") },
  { key: "trapeze", icon: "🤸", make: trapeze, items: it("rope", "bolt", "plank", "ladder", "paint", "gear") },
  { key: "ticket", icon: "🎫", make: B(ticketBooth), items: it("plank", "paint", "bulb", "bag", "key", "sign") },
  { key: "wagon", n: 2, icon: "🚐", make: B(circusWagon), items: it("plank", "paint", "car", "bulb", "key", "gear") },
  { key: "stall", n: 1, icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "drink", "apple") },
  { key: "carousel", icon: "🎠", make: carousel, items: it("gear", "paint", "bulb", "plank", "bolt", "spark") },
  { key: "foodtruck", icon: "🌮", make: foodTruck, items: it("cup", "drink", "car", "bulb", "bag", "basket") },
  { key: "wagon", n: 3, icon: "🚐", make: B(circusWagon), items: it("plank", "paint", "car", "bulb", "key", "gear") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "ring", n: 2, icon: "⭕", make: B(circusRing), items: it("sand", "plank", "paint", "bench", "rope", "ruler") },
  { key: "stall", n: 2, icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "drink", "apple") },
  { key: "billboard", icon: "📺", make: buildBillboard, items: it("paint", "bulb", "wire", "bolt", "plan", "spark") },
  { key: "fountain", icon: "⛲", make: buildCityFountain, items: it("water", "stone", "pipe", "cement", "bulb", "shell") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const PIRATE_STAGES = [
  { key: "wharf", icon: "⚓", global: true, make: B(wharf), items: it("plank", "rope", "bolt", "hammer", "anchor", "cement") },
  { key: "ship", n: 1, icon: "🏴‍☠️", make: pirateShip, items: it("plank", "rope", "paint", "anchor", "bolt", "wave") },
  { key: "tavern", icon: "🍺", make: B(pirateTavern), items: it("plank", "brick", "door", "cup", "basket", "bulb") },
  { key: "chest", n: 1, icon: "💰", make: B(treasureChest), items: it("plank", "gold", "gem", "key", "bolt", "rope") },
  { key: "nest", icon: "🔭", make: B(crowsNest), items: it("stone", "plank", "rope", "torch", "ladder", "bulb") },
  { key: "boats", icon: "⛵", make: buildBoats, items: it("boat", "rope", "plank", "anchor", "buoy", "wave") },
  { key: "chest", n: 2, icon: "💰", make: B(treasureChest), items: it("plank", "gold", "gem", "key", "bolt", "rope") },
  { key: "hut", n: 1, icon: "🛖", make: B(bungalow, 0xc9a878), items: it("plank", "straw", "door", "rope", "paint", "shell") },
  { key: "ship", n: 2, icon: "🏴‍☠️", make: pirateShip, items: it("plank", "rope", "paint", "anchor", "bolt", "wave") },
  { key: "lighthouse", icon: "🗼", make: buildLighthouse, items: it("stone", "paint", "bulb", "glass", "ladder", "wire") },
  { key: "palms", icon: "🌴", make: buildPalms, items: it("palm", "sprout", "water", "shears", "nut", "sand") },
  { key: "hut", n: 2, icon: "🛖", make: B(bungalow, 0xd8b98a), items: it("plank", "straw", "door", "rope", "paint", "shell") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "fish", "bag", "rope", "cup") },
  { key: "chest", n: 3, icon: "💰", make: B(treasureChest), items: it("plank", "gold", "gem", "key", "bolt", "rope") },
  { key: "pier", icon: "🌉", make: buildPier, items: it("plank", "rope", "bolt", "hammer", "anchor", "buoy") },
  { key: "buoys", icon: "🛟", make: harborBuoys, items: it("buoy", "rope", "paint", "bulb", "anchor", "wave") },
  { key: "beach", icon: "🏖️", make: buildBeach, items: it("sand", "shell", "water", "basket", "gloves", "sun") },
  { key: "beachlights", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const SHROOM_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "sprout", "gloves", "shears", "ruler", "basket") },
  { key: "shroomhouse", n: 1, icon: "🍄", make: B(mushroomHouse, 0xd9435a), items: it("sprout", "plank", "door", "glass", "paint", "seed") },
  { key: "glow", n: 1, icon: "✨", make: glowShrooms, items: it("sprout", "bulb", "spark", "water", "seed", "algae") },
  { key: "fairyring", icon: "⭕", make: fairyRing, items: it("sprout", "spark", "bulb", "seed", "shears", "candle") },
  { key: "shroomhouse", n: 2, icon: "🍄", make: B(mushroomHouse, 0x9a5ad4), items: it("sprout", "plank", "door", "glass", "paint", "seed") },
  { key: "shroombridge", icon: "🌉", make: B(mushroomBridge), items: it("sprout", "plank", "rope", "paint", "bolt", "spark") },
  { key: "pond", icon: "💧", make: buildPond, items: it("water", "stone", "fish", "lotus", "algae", "sand") },
  { key: "glow", n: 2, icon: "✨", make: glowShrooms, items: it("sprout", "bulb", "spark", "water", "seed", "algae") },
  { key: "shroomhouse", n: 3, icon: "🍄", make: B(mushroomHouse, 0x3fc4b4), items: it("sprout", "plank", "door", "glass", "paint", "seed") },
  { key: "fir", icon: "🌲", make: B(firGrove), items: it("tree", "sprout", "shears", "gloves", "basket", "nut") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "beds", icon: "🥬", make: buildBeds, items: it("seed", "nut", "sprout", "water", "basket", "worm") },
  { key: "shroomhouse", n: 4, icon: "🍄", make: B(mushroomHouse, 0xe8a83c), items: it("sprout", "plank", "door", "glass", "paint", "seed") },
  { key: "fairyring", n: 2, icon: "⭕", make: fairyRing, items: it("sprout", "spark", "bulb", "seed", "shears", "candle") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "apple", "bag", "rope", "cup") },
  { key: "glow", n: 3, icon: "✨", make: glowShrooms, items: it("sprout", "bulb", "spark", "water", "seed", "algae") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];


const SKI_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "sand", "gloves", "ruler", "hammer", "cart") },
  { key: "chalet", n: 1, icon: "🏡", make: B(chalet), items: it("plank", "brick", "door", "glass", "paint", "bulb") },
  { key: "skilift", icon: "🚡", make: skiLift, items: it("rope", "bolt", "gear", "crane", "paint", "wire") },
  { key: "rink", icon: "⛸️", make: resortRink, items: it("water", "cement", "bulb", "paint", "bench", "wire") },
  { key: "pines", n: 1, icon: "🌲", make: B(snowPines), items: it("tree", "sprout", "shears", "gloves", "basket", "water") },
  { key: "chalet", n: 2, icon: "🏡", make: B(chalet), items: it("plank", "brick", "door", "glass", "ladder", "key") },
  { key: "cafe", icon: "☕", make: buildCafe, items: it("cup", "bench", "umbrella", "glass", "paint", "drink") },
  { key: "pines", n: 2, icon: "🌲", make: B(snowPines), items: it("tree", "sprout", "shears", "gloves", "basket", "water") },
  { key: "chalet", n: 3, icon: "🏡", make: B(chalet), items: it("plank", "brick", "door", "glass", "paint", "bulb") },
  { key: "watchtower", icon: "🗼", make: B(watchtower), items: it("stone", "brick", "ladder", "torch", "rope", "paint") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "drink", "apple") },
  { key: "skilift", n: 2, icon: "🚡", make: skiLift, items: it("rope", "bolt", "gear", "crane", "paint", "wire") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "pines", n: 3, icon: "🌲", make: B(snowPines), items: it("tree", "sprout", "shears", "gloves", "basket", "water") },
  { key: "chapel", icon: "⛪", make: B(chapel), items: it("stone", "glass", "plank", "paint", "bulb", "ladder") },
  { key: "rink", n: 2, icon: "⛸️", make: resortRink, items: it("water", "cement", "bulb", "paint", "bench", "wire") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const TEA_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "sand", "gloves", "shears", "ruler", "basket") },
  { key: "terraces", n: 1, icon: "🍃", make: B(teaTerraces), items: it("sprout", "seed", "water", "shears", "basket", "worm") },
  { key: "teahouse", n: 1, icon: "🍵", make: B(teaHouse), items: it("plank", "paper", "door", "glass", "paint", "bulb") },
  { key: "racks", n: 1, icon: "🗄️", make: B(dryingRacks), items: it("plank", "bolt", "basket", "rope", "gloves", "sun") },
  { key: "teamill", icon: "⚙️", make: teaMill, items: it("gear", "plank", "water", "bolt", "stone", "rope") },
  { key: "terraces", n: 2, icon: "🍃", make: B(teaTerraces), items: it("sprout", "seed", "water", "shears", "basket", "worm") },
  { key: "pond", icon: "💧", make: buildPond, items: it("water", "stone", "fish", "lotus", "algae", "sand") },
  { key: "teahouse", n: 2, icon: "🍵", make: B(teaHouse), items: it("plank", "paper", "door", "glass", "paint", "bulb") },
  { key: "racks", n: 2, icon: "🗄️", make: B(dryingRacks), items: it("plank", "bolt", "basket", "rope", "gloves", "sun") },
  { key: "bridge", icon: "🌉", make: B(bridge), items: it("plank", "rope", "stone", "hammer", "bolt", "water") },
  { key: "terraces", n: 3, icon: "🍃", make: B(teaTerraces), items: it("sprout", "seed", "water", "shears", "basket", "worm") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "drink", "apple") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "orchard", icon: "🌳", make: buildOrchard, items: it("tree", "sprout", "water", "shears", "basket", "apple") },
  { key: "teamill", n: 2, icon: "⚙️", make: teaMill, items: it("gear", "plank", "water", "bolt", "stone", "rope") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "beds", icon: "🥬", make: buildBeds, items: it("seed", "nut", "sprout", "water", "basket", "worm") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const CLOCK_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "brick", "cement", "ruler", "plan", "hammer") },
  { key: "clocktower", icon: "🕰️", make: clockTower, items: it("brick", "gear", "glass", "bolt", "plan", "bulb") },
  { key: "watchshop", n: 1, icon: "🔧", make: B(watchmakerShop), items: it("brick", "glass", "door", "gear", "paint", "screw") },
  { key: "chimes", n: 1, icon: "🔔", make: streetChimes, items: it("bolt", "wire", "paint", "bulb", "gear", "cement") },
  { key: "sundial", icon: "☀️", make: B(sundial), items: it("stone", "cement", "ruler", "gold", "plan", "gloves") },
  { key: "watchshop", n: 2, icon: "🔧", make: B(watchmakerShop), items: it("brick", "glass", "door", "gear", "paint", "screw") },
  { key: "fountain", icon: "⛲", make: buildCityFountain, items: it("water", "stone", "pipe", "cement", "bulb", "shell") },
  { key: "house", n: 1, icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.6, floors: 2, body: 0xd8c9a8, roof: 0x7a5a3a }), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "chimes", n: 2, icon: "🔔", make: streetChimes, items: it("bolt", "wire", "paint", "bulb", "gear", "cement") },
  { key: "cafe", icon: "☕", make: buildCafe, items: it("cup", "bench", "umbrella", "glass", "paint", "drink") },
  { key: "house", n: 2, icon: "🏠", make: B(dwelling, { w: 3.2, d: 2.8, floors: 3, body: 0xc4b8a4, roof: 0x6e6a66 }), items: it("brick", "plank", "door", "glass", "ladder", "lift") },
  { key: "watchshop", n: 3, icon: "🔧", make: B(watchmakerShop), items: it("brick", "glass", "door", "gear", "paint", "screw") },
  { key: "billboard", icon: "📺", make: buildBillboard, items: it("paint", "bulb", "wire", "bolt", "plan", "spark") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "sundial", n: 2, icon: "☀️", make: B(sundial), items: it("stone", "cement", "ruler", "gold", "plan", "gloves") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "drink", "apple") },
  { key: "chapel", icon: "⛪", make: B(chapel), items: it("stone", "glass", "plank", "paint", "bulb", "ladder") },
  { key: "streetlamps", icon: "💡", global: true, make: buildStreetLamps, items: it("bulb", "wire", "cement", "screw", "spark", "torch") },
];


const BEE_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "sand", "gloves", "shears", "ruler", "basket") },
  { key: "hive", n: 1, icon: "🐝", make: beehive, items: it("plank", "hammer", "gloves", "bolt", "paint", "straw") },
  { key: "meadow", n: 1, icon: "🌼", make: B(meadow), items: it("seed", "sprout", "water", "shears", "basket", "worm") },
  { key: "honeyhouse", icon: "🍯", make: B(honeyHouse), items: it("plank", "brick", "door", "glass", "basket", "cup") },
  { key: "hive", n: 2, icon: "🐝", make: beehive, items: it("plank", "hammer", "gloves", "bolt", "paint", "straw") },
  { key: "combframe", n: 1, icon: "🍮", make: B(honeycombFrame), items: it("plank", "gloves", "basket", "cup", "rope", "bolt") },
  { key: "meadow", n: 2, icon: "🌼", make: B(meadow), items: it("seed", "sprout", "water", "shears", "basket", "worm") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "hive", n: 3, icon: "🐝", make: beehive, items: it("plank", "hammer", "gloves", "bolt", "paint", "straw") },
  { key: "orchard", icon: "🌳", make: buildOrchard, items: it("tree", "sprout", "water", "shears", "basket", "apple") },
  { key: "combframe", n: 2, icon: "🍮", make: B(honeycombFrame), items: it("plank", "gloves", "basket", "cup", "rope", "bolt") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "apple", "drink") },
  { key: "house", icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.6, body: 0xe8cf98, roof: 0xb08f44, chimney: true }), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "meadow", n: 3, icon: "🌼", make: B(meadow), items: it("seed", "sprout", "water", "shears", "basket", "worm") },
  { key: "pen", icon: "🐑", make: B(pen), items: it("plank", "rope", "straw", "hammer", "water", "gloves") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "beds", icon: "🥬", make: buildBeds, items: it("seed", "nut", "sprout", "water", "basket", "worm") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const STAR_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "cement", "ruler", "plan", "gloves", "hammer") },
  { key: "dome", icon: "🔭", make: observatoryDome, items: it("cement", "glass", "gear", "bolt", "plan", "wire") },
  { key: "hut", n: 1, icon: "🏠", make: B(astronomerHut), items: it("brick", "glass", "door", "paint", "bulb", "plan") },
  { key: "radiodish", n: 1, icon: "📡", make: radioDish, items: it("bolt", "wire", "gear", "crane", "plan", "screw") },
  { key: "chart", n: 1, icon: "✨", make: starChart, items: it("stone", "paint", "bulb", "plan", "spark", "gold") },
  { key: "radiodish", n: 2, icon: "📡", make: radioDish, items: it("bolt", "wire", "gear", "crane", "plan", "screw") },
  { key: "hut", n: 2, icon: "🏠", make: B(astronomerHut), items: it("brick", "glass", "door", "paint", "bulb", "plan") },
  { key: "watertower", icon: "🗼", make: buildWaterTower, items: it("pipe", "bolt", "ladder", "water", "paint", "crane") },
  { key: "chart", n: 2, icon: "✨", make: starChart, items: it("stone", "paint", "bulb", "plan", "spark", "gold") },
  { key: "warehouse", icon: "📦", make: B(warehouse), items: it("cement", "bolt", "door", "crane", "paint", "glass") },
  { key: "radar", icon: "📶", make: radar, items: it("wire", "bolt", "gear", "plan", "screw", "bulb") },
  { key: "cafe", icon: "☕", make: buildCafe, items: it("cup", "bench", "umbrella", "glass", "paint", "drink") },
  { key: "hut", n: 3, icon: "🏠", make: B(astronomerHut), items: it("brick", "glass", "door", "paint", "bulb", "plan") },
  { key: "parking", icon: "🅿️", make: buildParking, items: it("car", "paint", "cement", "cone", "sign", "ruler") },
  { key: "chart", n: 3, icon: "✨", make: starChart, items: it("stone", "paint", "bulb", "plan", "spark", "gold") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "billboard", icon: "📺", make: buildBillboard, items: it("paint", "bulb", "wire", "bolt", "plan", "spark") },
  { key: "streetlamps", icon: "💡", global: true, make: buildStreetLamps, items: it("bulb", "wire", "cement", "screw", "spark", "torch") },
];

const ART_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "brick", "paint", "ruler", "plan", "hammer") },
  { key: "gallery", n: 1, icon: "🖼️", make: B(artGallery), items: it("glass", "cement", "door", "paint", "bulb", "plan") },
  { key: "mural", n: 1, icon: "🎨", make: B(muralWall), items: it("paint", "brick", "ladder", "gloves", "shears", "spark") },
  { key: "studio", n: 1, icon: "🗿", make: sculptorStudio, items: it("stone", "glass", "hammer", "gloves", "plank", "paint") },
  { key: "kinetic", icon: "🌀", make: kineticSculpture, items: it("gear", "bolt", "paint", "crane", "wire", "gold") },
  { key: "mural", n: 2, icon: "🎨", make: B(muralWall), items: it("paint", "brick", "ladder", "gloves", "shears", "spark") },
  { key: "gallery", n: 2, icon: "🖼️", make: B(artGallery), items: it("glass", "cement", "door", "paint", "bulb", "plan") },
  { key: "cafe", icon: "☕", make: buildCafe, items: it("cup", "bench", "umbrella", "glass", "paint", "drink") },
  { key: "studio", n: 2, icon: "🗿", make: sculptorStudio, items: it("stone", "glass", "hammer", "gloves", "plank", "paint") },
  { key: "fountain", icon: "⛲", make: buildCityFountain, items: it("water", "stone", "pipe", "cement", "bulb", "shell") },
  { key: "mural", n: 3, icon: "🎨", make: B(muralWall), items: it("paint", "brick", "ladder", "gloves", "shears", "spark") },
  { key: "house", n: 1, icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.6, floors: 2, body: 0xf0e8d8, roof: 0xd94f4f }), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "kinetic", n: 2, icon: "🌀", make: kineticSculpture, items: it("gear", "bolt", "paint", "crane", "wire", "gold") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "paint", "paper") },
  { key: "gallery", n: 3, icon: "🖼️", make: B(artGallery), items: it("glass", "cement", "door", "paint", "bulb", "plan") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "billboard", icon: "📺", make: buildBillboard, items: it("paint", "bulb", "wire", "bolt", "plan", "spark") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];


const SEA_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "sand", "shell", "gloves", "ruler", "algae") },
  { key: "seadome", n: 1, icon: "🫧", make: seaDome, items: it("glass", "bolt", "pipe", "cement", "wire", "water") },
  { key: "coral", n: 1, icon: "🪸", make: coralGarden, items: it("shell", "algae", "sprout", "water", "sand", "fish") },
  { key: "wreck", icon: "🚢", make: B(sunkenWreck), items: it("plank", "rope", "anchor", "algae", "gold", "shell") },
  { key: "beacon", icon: "🔆", make: seaBeacon, items: it("bulb", "glass", "wire", "cement", "paint", "spark") },
  { key: "seadome", n: 2, icon: "🫧", make: seaDome, items: it("glass", "bolt", "pipe", "cement", "wire", "water") },
  { key: "coral", n: 2, icon: "🪸", make: coralGarden, items: it("shell", "algae", "sprout", "water", "sand", "fish") },
  { key: "pond", icon: "💧", make: buildPond, items: it("water", "stone", "fish", "lotus", "algae", "sand") },
  { key: "seadome", n: 3, icon: "🫧", make: seaDome, items: it("glass", "bolt", "pipe", "cement", "wire", "water") },
  { key: "buoys", icon: "🛟", make: harborBuoys, items: it("buoy", "rope", "paint", "bulb", "anchor", "wave") },
  { key: "coral", n: 3, icon: "🪸", make: coralGarden, items: it("shell", "algae", "sprout", "water", "sand", "fish") },
  { key: "warehouse", icon: "📦", make: B(warehouse), items: it("cement", "bolt", "door", "crane", "paint", "glass") },
  { key: "wreck", n: 2, icon: "🚢", make: B(sunkenWreck), items: it("plank", "rope", "anchor", "algae", "gold", "shell") },
  { key: "watertower", icon: "🗼", make: buildWaterTower, items: it("pipe", "bolt", "ladder", "water", "paint", "crane") },
  { key: "beacon", n: 2, icon: "🔆", make: seaBeacon, items: it("bulb", "glass", "wire", "cement", "paint", "spark") },
  { key: "fishmarket", icon: "🐟", make: fishMarket, items: it("fish", "basket", "plank", "cup", "bag", "shell") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "algae") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

const MUSIC_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "brick", "paint", "ruler", "plan", "hammer") },
  { key: "bandshell", icon: "🎶", make: bandShell, items: it("plank", "paint", "bulb", "bolt", "wire", "cement") },
  { key: "musicshop", n: 1, icon: "🎸", make: B(musicShop), items: it("plank", "glass", "door", "paint", "wire", "bulb") },
  { key: "piano", n: 1, icon: "🎹", make: B(streetPiano), items: it("plank", "paint", "wire", "bolt", "gloves", "bench") },
  { key: "carillon", icon: "🔔", make: carillon, items: it("brick", "gold", "rope", "bolt", "gear", "plan") },
  { key: "musicshop", n: 2, icon: "🎸", make: B(musicShop), items: it("plank", "glass", "door", "paint", "wire", "bulb") },
  { key: "cafe", icon: "☕", make: buildCafe, items: it("cup", "bench", "umbrella", "glass", "paint", "drink") },
  { key: "piano", n: 2, icon: "🎹", make: B(streetPiano), items: it("plank", "paint", "wire", "bolt", "gloves", "bench") },
  { key: "house", n: 1, icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.6, floors: 2, body: 0xe8d8b8, roof: 0x8f4a6a }), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "fountain", icon: "⛲", make: buildCityFountain, items: it("water", "stone", "pipe", "cement", "bulb", "shell") },
  { key: "musicshop", n: 3, icon: "🎸", make: B(musicShop), items: it("plank", "glass", "door", "paint", "wire", "bulb") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "piano", n: 3, icon: "🎹", make: B(streetPiano), items: it("plank", "paint", "wire", "bolt", "gloves", "bench") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "paper", "drink") },
  { key: "house", n: 2, icon: "🏠", make: B(dwelling, { w: 3.2, d: 2.8, floors: 3, body: 0xd8c4a8, roof: 0x6a4f8f }), items: it("brick", "plank", "door", "glass", "ladder", "lift") },
  { key: "billboard", icon: "📺", make: buildBillboard, items: it("paint", "bulb", "wire", "bolt", "plan", "spark") },
  { key: "park", icon: "🌳", make: buildParkSquare, items: it("tree", "sprout", "water", "bench", "shears", "basket") },
  { key: "streetlamps", icon: "💡", global: true, make: buildStreetLamps, items: it("bulb", "wire", "cement", "screw", "spark", "torch") },
];

const POTTERY_STAGES = [
  { key: "path", icon: "🪨", global: true, make: buildPath, items: it("stone", "sand", "gloves", "ruler", "cart", "hammer") },
  { key: "wheel", n: 1, icon: "🏺", make: potteryWheel, items: it("plank", "gear", "water", "gloves", "sand", "paint") },
  { key: "kiln", n: 1, icon: "🔥", make: kiln, items: it("brick", "torch", "cement", "gloves", "log", "sand") },
  { key: "potracks", n: 1, icon: "🗄️", make: B(potteryRacks), items: it("plank", "bolt", "basket", "gloves", "rope", "sun") },
  { key: "claypit", icon: "⛏️", make: B(clayPit), items: it("sand", "water", "cart", "gloves", "hammer", "stone") },
  { key: "wheel", n: 2, icon: "🏺", make: potteryWheel, items: it("plank", "gear", "water", "gloves", "sand", "paint") },
  { key: "house", n: 1, icon: "🏠", make: B(dwelling, { w: 3.0, d: 2.6, body: 0xd8b48a, roof: 0x94512a, chimney: true }), items: it("brick", "plank", "door", "glass", "paint", "key") },
  { key: "potracks", n: 2, icon: "🗄️", make: B(potteryRacks), items: it("plank", "bolt", "basket", "gloves", "rope", "sun") },
  { key: "kiln", n: 2, icon: "🔥", make: kiln, items: it("brick", "torch", "cement", "gloves", "log", "sand") },
  { key: "well", icon: "🪣", make: buildWell, items: it("stone", "sand", "rope", "chain", "plank", "water") },
  { key: "wheel", n: 3, icon: "🏺", make: potteryWheel, items: it("plank", "gear", "water", "gloves", "sand", "paint") },
  { key: "stall", icon: "🧺", make: B(marketStall), items: it("plank", "basket", "cup", "bag", "paint", "apple") },
  { key: "house", n: 2, icon: "🏠", make: B(dwelling, { w: 3.2, d: 2.8, floors: 2, body: 0xc4a078, roof: 0x7a4020 }), items: it("brick", "plank", "door", "glass", "ladder", "key") },
  { key: "potracks", n: 3, icon: "🗄️", make: B(potteryRacks), items: it("plank", "bolt", "basket", "gloves", "rope", "sun") },
  { key: "firewood", icon: "🪵", make: B(firewood), items: it("log", "saw", "gloves", "rope", "cart", "hammer") },
  { key: "gazebo", icon: "🎪", make: B(gazebo), items: it("plank", "paint", "bolt", "bench", "bulb", "rope") },
  { key: "beds", icon: "🥬", make: buildBeds, items: it("seed", "nut", "sprout", "water", "basket", "worm") },
  { key: "lanterns", icon: "✨", global: true, make: buildLanterns, items: it("bulb", "wire", "candle", "torch", "screw", "spark") },
];

export const WORLDS = [
  makeWorld({
    key: "village",
    icon: "🌾",
    sky: 0x9fdcff,
    light: { sun: 0.72, hemiSky: 0xc4ecff, hemiGround: 0x6fbf4a, hemi: 0.32, ambient: 0.12 },
    ground: { top: C.grass, side: C.soil, tip: C.soilDark, tuft: C.grassDark },
    stages: VILLAGE_STAGES,
    layout: { corridor: 0, minGap: 4.5, startR: 5.0, radialGap: 4.6 },
  }),
  makeWorld({
    key: "town",
    icon: "🏘️",
    sky: 0x8fd4f7,
    light: { sun: 0.70, hemiSky: 0xc4ecff, hemiGround: 0x6fbf4a, hemi: 0.32, ambient: 0.12 },
    ground: { top: 0x74d14a, side: 0xa8632f, tip: 0x854a22, tuft: 0x4fc42a },
    stages: TOWN_STAGES,
    layout: { corridor: 4.3, minGap: 4.5, startR: 6.2, radialGap: 4.6 },
  }),
  makeWorld({
    key: "city",
    icon: "🏙️",
    sky: 0x9ecfe8,
    light: { sun: 0.70, hemiSky: 0xcfeaff, hemiGround: 0x8a99a3, hemi: 0.34, ambient: 0.13 },
    ground: { top: 0xb4bfc4, side: 0x8a949e, tip: 0x6e7880, tuft: 0x7ec44a },
    stages: CITY_STAGES,
    layout: { corridor: 5.0, minGap: 4.6, startR: 6.6, radialGap: 4.8 },
  }),
  makeWorld({
    key: "castle",
    icon: "🏰",
    sky: 0x9ec4e0,
    light: { sun: 0.70, sunColor: 0xfff2d8, hemiSky: 0xc4e0f7, hemiGround: 0x7a9a5a, hemi: 0.32, ambient: 0.13 },
    ground: { top: 0x6fc44a, side: 0x9a7f5a, tip: 0x7a6244, tuft: 0x4fb42a },
    stages: CASTLE_STAGES,
    layout: { corridor: 0, minGap: 5.2, startR: 5.8, radialGap: 5.3 },
  }),
  makeWorld({
    key: "antique",
    icon: "🏛️",
    sky: 0x8fd8f0,
    light: { sun: 0.72, sunColor: 0xfff6e0, hemiSky: 0xcfeaff, hemiGround: 0xc9b48a, hemi: 0.32, ambient: 0.12 },
    ground: { top: 0x9fc46a, side: 0xc9a878, tip: 0xa88a5a, tuft: 0x8fb44a },
    stages: ANTIQUE_STAGES,
    layout: { corridor: 0, minGap: 5.4, startR: 6.0, radialGap: 5.5 },
  }),
  makeWorld({
    key: "winter",
    icon: "❄️",
    sky: 0xa8d8f5,
    snow: true,
    light: { sun: 0.60, sunColor: 0xf2f8ff, hemiSky: 0xd8eeff, hemiGround: 0xc4d4e0, hemi: 0.34, ambient: 0.14, sunPos: [7, 15, 10] },
    ground: { top: 0xf7fcff, side: 0xcfdce8, tip: 0xafc0d0, tuft: 0xffffff },
    stages: WINTER_STAGES,
    layout: { corridor: 0, minGap: 4.6, startR: 5.2, radialGap: 4.7 },
  }),
  makeWorld({
    key: "ski",
    icon: "⛷️",
    sky: 0xbfe0f0,
    light: { sun: 0.62, sunColor: 0xfff6e8, hemiSky: 0xd8f0ff, hemiGround: 0xdfe8ee, hemi: 0.38, ambient: 0.14 },
    ground: { top: 0xf2fbff, side: 0xd4e4ee, tip: 0xb4cddc, tuft: 0x9fd4e8 },
    stages: SKI_STAGES,
    layout: { corridor: 0, minGap: 5.4, startR: 6.0, radialGap: 5.5 },
  }),
  makeWorld({
    key: "pottery",
    icon: "🏺",
    sky: 0xe0c49a,
    light: { sun: 0.70, sunColor: 0xfff2d8, hemiSky: 0xf0d8b0, hemiGround: 0xa8764a, hemi: 0.33, ambient: 0.13 },
    ground: { top: 0xc49a6a, side: 0xa8764a, tip: 0x8a5c34, tuft: 0x9fae5a },
    stages: POTTERY_STAGES,
    layout: { corridor: 0, minGap: 5.2, startR: 5.8, radialGap: 5.3 },
  }),
  makeWorld({
    key: "bee",
    icon: "🐝",
    sky: 0xa8e0f0,
    light: { sun: 0.70, sunColor: 0xfff8dc, hemiSky: 0xcdf0ff, hemiGround: 0x8faa4a, hemi: 0.33, ambient: 0.13 },
    ground: { top: 0x86bf4a, side: 0xa8874a, tip: 0x86672f, tuft: 0xd4c43a },
    stages: BEE_STAGES,
    layout: { corridor: 0, minGap: 5.2, startR: 5.8, radialGap: 5.3 },
  }),
  makeWorld({
    key: "tea",
    icon: "🍵",
    sky: 0xa8dcc4,
    light: { sun: 0.66, sunColor: 0xfff8e0, hemiSky: 0xc4f0d8, hemiGround: 0x6a8a4a, hemi: 0.34, ambient: 0.13 },
    ground: { top: 0x74b04a, side: 0x8a6a45, tip: 0x6a5030, tuft: 0x5f9e3a },
    stages: TEA_STAGES,
    layout: { corridor: 0, minGap: 5.2, startR: 5.8, radialGap: 5.3 },
  }),
  makeWorld({
    key: "sakura",
    icon: "🌸",
    sky: 0xffd4e8,
    petals: true,
    light: { sun: 0.68, sunColor: 0xfff0f2, hemiSky: 0xffdcec, hemiGround: 0x8fc46a, hemi: 0.33, ambient: 0.14 },
    ground: { top: 0x7fd455, side: 0xa8784a, tip: 0x86603a, tuft: 0xffb7d5 },
    stages: SAKURA_STAGES,
    layout: { corridor: 0, minGap: 4.8, startR: 5.4, radialGap: 4.9 },
  }),
  makeWorld({
    key: "night",
    icon: "🌃",
    sky: 0x1a0b3d,
    night: true,
    light: { sun: 0.22, sunColor: 0x8f6fff, hemiSky: 0x4a2a8f, hemiGround: 0x1a1030, hemi: 0.30, ambient: 0.08, sunPos: [-12, 14, -8] },
    ground: { top: 0x3d2a6b, side: 0x2a1c4a, tip: 0x1e1236, tuft: 0x6f3fd4 },
    stages: NIGHT_STAGES,
    layout: { corridor: 5.0, minGap: 4.6, startR: 6.6, radialGap: 4.8 },
  }),
  makeWorld({
    key: "airport",
    icon: "✈️",
    sky: 0x8fcdf0,
    light: { sun: 0.72, sunColor: 0xfff8ea, hemiSky: 0xcfeaff, hemiGround: 0x7fbf5a, hemi: 0.32, ambient: 0.12 },
    ground: { top: 0x74c44a, side: 0xa8843f, tip: 0x86682c, tuft: 0x5fc433 },
    stages: AIRPORT_STAGES,
    layout: { corridor: 5.6, minGap: 5.0, startR: 7.2, radialGap: 5.2 },
  }),
  makeWorld({
    key: "desert",
    icon: "🏜️",
    sky: 0xffd98f,
    light: { sun: 0.70, sunColor: 0xfff2c4, hemiSky: 0xffe8b8, hemiGround: 0xe0a84a, hemi: 0.30, ambient: 0.11, sunPos: [11, 17, 5] },
    ground: { top: 0xffd97a, side: 0xe8a83c, tip: 0xc4842a, tuft: 0xffc44a },
    stages: DESERT_STAGES,
    layout: { corridor: 0, minGap: 4.7, startR: 5.2, radialGap: 4.8 },
  }),
  makeWorld({
    key: "park",
    icon: "🎡",
    sky: 0x8fdcff,
    light: { sun: 0.72, sunColor: 0xfff8e8, hemiSky: 0xd4f0ff, hemiGround: 0x7fd44a, hemi: 0.32, ambient: 0.12 },
    ground: { top: 0x7ee055, side: 0xb56a33, tip: 0x8f5024, tuft: 0x4fd42a },
    stages: PARK_STAGES,
    layout: { corridor: 0, minGap: 5.4, startR: 6.0, radialGap: 5.5 },
  }),
  makeWorld({
    key: "circus",
    icon: "🎪",
    sky: 0x8fd4f0,
    light: { sun: 0.70, sunColor: 0xfff8e4, hemiSky: 0xd4f0ff, hemiGround: 0x7fc44a, hemi: 0.33, ambient: 0.13 },
    ground: { top: 0x7fd455, side: 0xb56a33, tip: 0x8f5024, tuft: 0x4fd42a },
    stages: CIRCUS_STAGES,
    layout: { corridor: 0, minGap: 5.6, startR: 6.2, radialGap: 5.7 },
  }),
  makeWorld({
    key: "shroom",
    icon: "🍄",
    sky: 0x6f5a9e,
    light: { sun: 0.40, sunColor: 0xbfa8ff, hemiSky: 0x7f6ac4, hemiGround: 0x2f4a3a, hemi: 0.36, ambient: 0.16, sunPos: [-9, 14, 6] },
    ground: { top: 0x3f7a4a, side: 0x5a4a3a, tip: 0x3e3228, tuft: 0x6fd4a4 },
    stages: SHROOM_STAGES,
    layout: { corridor: 0, minGap: 5.2, startR: 5.8, radialGap: 5.3 },
  }),
  makeWorld({
    key: "mine",
    icon: "⛏️",
    sky: 0xa8bcc8,
    light: { sun: 0.66, sunColor: 0xfff0dc, hemiSky: 0xc4d8e4, hemiGround: 0x8a8074, hemi: 0.33, ambient: 0.14 },
    ground: { top: 0x9a9484, side: 0x7a7266, tip: 0x5e584e, tuft: 0x8fa86a },
    stages: MINE_STAGES,
    layout: { corridor: 0, minGap: 5.0, startR: 5.6, radialGap: 5.1 },
  }),
  makeWorld({
    key: "jungle",
    icon: "🌴",
    sky: 0x7fd4c4,
    light: { sun: 0.68, sunColor: 0xfff8e0, hemiSky: 0xb4f0e0, hemiGround: 0x3f7a3a, hemi: 0.34, ambient: 0.13 },
    ground: { top: 0x4fb03f, side: 0x7a5a34, tip: 0x5e4426, tuft: 0x2f8f2a },
    stages: JUNGLE_STAGES,
    layout: { corridor: 0, minGap: 5.2, startR: 5.8, radialGap: 5.3 },
  }),
  makeWorld({
    key: "volcano",
    icon: "🌋",
    sky: 0x6a4a5e,
    light: { sun: 0.48, sunColor: 0xffb08a, hemiSky: 0x8f5a6a, hemiGround: 0x4a3a44, hemi: 0.34, ambient: 0.16, sunPos: [8, 13, -6] },
    ground: { top: 0x5a5060, side: 0x3f3a48, tip: 0x2e2a36, tuft: 0x8a5a4a },
    stages: VOLCANO_STAGES,
    layout: { corridor: 0, minGap: 5.0, startR: 6.4, radialGap: 5.1 },
  }),
  makeWorld({
    key: "railway",
    icon: "🚂",
    sky: 0x9fd4ea,
    light: { sun: 0.70, sunColor: 0xfff4de, hemiSky: 0xcfeaff, hemiGround: 0x7fa85a, hemi: 0.32, ambient: 0.13 },
    ground: { top: 0x7fc45a, side: 0xa8845a, tip: 0x866a44, tuft: 0x5fb43a },
    stages: RAILWAY_STAGES,
    layout: { corridor: 2.6, minGap: 5.2, startR: 6.4, radialGap: 5.3 },
  }),
  makeWorld({
    key: "star",
    icon: "🔭",
    sky: 0x2a3560,
    light: { sun: 0.42, sunColor: 0xbfc8ff, hemiSky: 0x4a5a9e, hemiGround: 0x3a4050, hemi: 0.36, ambient: 0.17, sunPos: [-8, 15, 5] },
    ground: { top: 0x5a6070, side: 0x44495a, tip: 0x33384a, tuft: 0x6a7a9e },
    stages: STAR_STAGES,
    layout: { corridor: 0, minGap: 5.6, startR: 6.4, radialGap: 5.7 },
  }),
  makeWorld({
    key: "sea",
    icon: "🫧",
    sky: 0x2f7f9e,
    light: { sun: 0.46, sunColor: 0xaee4f5, hemiSky: 0x5fc4e0, hemiGround: 0x2a5a70, hemi: 0.40, ambient: 0.16 },
    ground: { top: 0xd8cfa8, side: 0xa89c74, tip: 0x8a7f58, tuft: 0x4fbfa8 },
    stages: SEA_STAGES,
    layout: { corridor: 0, minGap: 5.4, startR: 6.0, radialGap: 5.5 },
  }),
  makeWorld({
    key: "music",
    icon: "🎶",
    sky: 0xd8b4e0,
    light: { sun: 0.66, sunColor: 0xfff0e8, hemiSky: 0xf0d0f0, hemiGround: 0xb4a08a, hemi: 0.34, ambient: 0.13 },
    ground: { top: 0xbfae94, side: 0x9e8c72, tip: 0x7f7059, tuft: 0xc47fb4 },
    stages: MUSIC_STAGES,
    layout: { corridor: 0, minGap: 5.4, startR: 6.0, radialGap: 5.5 },
  }),
  makeWorld({
    key: "art",
    icon: "🎨",
    sky: 0xf0c4d8,
    light: { sun: 0.68, sunColor: 0xfff4e8, hemiSky: 0xffd8e8, hemiGround: 0xc4b8a8, hemi: 0.34, ambient: 0.13 },
    ground: { top: 0xc9c2b0, side: 0xa89e8a, tip: 0x8a8070, tuft: 0xd4749a },
    stages: ART_STAGES,
    layout: { corridor: 0, minGap: 5.4, startR: 6.0, radialGap: 5.5 },
  }),
  makeWorld({
    key: "clock",
    icon: "🕰️",
    sky: 0xc4bcd8,
    light: { sun: 0.64, sunColor: 0xfff0d8, hemiSky: 0xd8d0e8, hemiGround: 0xa89880, hemi: 0.34, ambient: 0.14 },
    ground: { top: 0xb4a894, side: 0x968a76, tip: 0x7a6f5e, tuft: 0x8faa6a },
    stages: CLOCK_STAGES,
    layout: { corridor: 0, minGap: 5.4, startR: 6.0, radialGap: 5.5 },
  }),
  makeWorld({
    key: "harbor",
    icon: "⚓",
    sky: 0x7fc8ea,
    light: { sun: 0.70, sunColor: 0xfff6e4, hemiSky: 0xb4e4ff, hemiGround: 0x6a8a9a, hemi: 0.32, ambient: 0.13 },
    ground: { top: 0x8a9aa4, side: 0x77848e, tip: 0x5f6a75, tuft: 0x6fbf5a },
    stages: HARBOR_STAGES,
    layout: { corridor: 0, minGap: 5.4, startR: 6.2, radialGap: 5.5 },
  }),
  makeWorld({
    key: "pirate",
    icon: "🏴‍☠️",
    sky: 0x7fc0e0,
    light: { sun: 0.68, sunColor: 0xfff4d8, hemiSky: 0xb4e4ff, hemiGround: 0xc9a878, hemi: 0.33, ambient: 0.13 },
    ground: { top: 0xe8cf98, side: 0xc9a468, tip: 0xa8844a, tuft: 0x7fc44a },
    stages: PIRATE_STAGES,
    layout: { corridor: 0, minGap: 5.4, startR: 6.0, radialGap: 5.5 },
  }),
  makeWorld({
    key: "space",
    icon: "🚀",
    sky: 0xbcd4e8,
    light: { sun: 0.70, sunColor: 0xfffaf0, hemiSky: 0xd8ecff, hemiGround: 0xa89c8a, hemi: 0.32, ambient: 0.13 },
    ground: { top: 0xc4b8a4, side: 0xa89880, tip: 0x8a7c66, tuft: 0x9aae7a },
    stages: SPACE_STAGES,
    layout: { corridor: 0, minGap: 5.6, startR: 6.4, radialGap: 5.7 },
  }),
  makeWorld({
    key: "resort",
    icon: "🏖️",
    sky: 0x6fdcf5,
    light: { sun: 0.70, sunColor: 0xfff8e0, hemiSky: 0xa8f0ff, hemiGround: 0xffd97a, hemi: 0.31, ambient: 0.12 },
    ground: { top: 0xffe8a8, side: 0xe8c47a, tip: 0xc4a055, tuft: 0x6fd44a },
    stages: RESORT_STAGES,
    layout: { corridor: 0, minGap: 4.5, startR: 5.0, radialGap: 4.6 },
  }),
];

/* всего уровней в игре */
export const TOTAL_LEVELS = WORLDS.reduce((s, w) => s + w.stages.length, 0);
